### ISSUE TITLE
[FO4] Changing an NVNM's Parent Worldspace does not update the type of NVNM Parent

### ISSUE THREAD

**Issue by Infernio** [TES5Edit/TES5Edit#1026]
**What is the version of xEdit you are using?**
FO4Edit 4.1.4b EXTREMELY EXPERIMENTAL (CF8D7AB0) starting session 2022-07-28 21:52:33

**Describe the bug**
If you change the `NVNM \ Parent Worldspace` from `NULL` to an actual worldspace (or vice versa), the `NVNM \ Parent` entry right below does not update its type correctly.

**To reproduce**
1. Load DLCworkshop01.esm
1. Navigate to record `02000C03`
1. Copy the record as an override into a new plugin
1. Scroll down to the `NVNM` subrecord, note how the `Parent Worldspace` is set to `NULL`
1. Change it to `Commonwealth "Commonwealth" [WRLD:0000003C]`
1. Note how the `Parent` entry right below it is now empty and can't be interacted with
1. Close xEdit, save the plugin and reopen it in xEdit
1. Note how the `Parent` entry is now correct
1. Change the `Parent Worldspace` back to `NULL`
1. Note how you can now interact with both the `CELL` FormID field and the two coordinate integers

**Expected behavior**
The type of the `Parent` field should be updated as soon as the user alters the value of the `Parent Worldspace` field.

**Screenshots**
![image](https://user-images.githubusercontent.com/2845240/181626343-805156b2-9e33-4f4c-92fd-a8afd0e914c0.png)

*(After completing all the 'To reproduce' steps above. Both the `Parent Cell` and the `Coordinates` can be interacted with.)*

**Comment by ElminsterAU** [comment]
These fields shouldn't really ever be edited at all, because they depend on what CELL children group this particular record is stored in, and xEdit really isn't designed to create new NAVM records at all.

I do acknowledge that the described behaviour is a bug, but don't think the effort required to fix this is worth it.

I don't intent to fix it except if someone can point out a workflow where this bug occurs when users are making normal, useful, edits.
