### ISSUE TITLE
I can't open any mod [An error occured while modules. Editing is disabled.Check the message log and correct the error.]

### ISSUE THREAD

**Issue by neeeetuo** [TES5Edit/TES5Edit#1046]
**What is the version of xEdit you are using?**
Copy the first line from your xEdit messages window.

**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by neeeetuo** [comment]
SSEEdit 4.0.4 (103758D4) starting session 2022-10-11 15:12:12

**Comment by neeeetuo** [comment]
> **What is the version of xEdit you are using?**SSEEdit 4.0.4 (103758D4) starting session 2022-10-11 15:12:12
> 
> **Describe the bug**I can't open any mod.
> 
> **To reproduce** I USE
> 
>1 I opened sseedit with mo2
2sseedit shows me the list of mods
3I click on any mod
4 error
> 
> **Expected behavior** Anyway, I want to be able to work with sseedit and I hope you can help me，please
> 
> **Screenshots** ![12](https://user-images.githubusercontent.com/96467273/195024411-953a13f4-0e0a-457b-9217-390dd16cbdaa.png)
> 
> **Additional context**
I'm sorry that my English is not good, I have not used github for several times, but I like to play skyrim, please help me solve it

**Comment by yarrmateys** [comment]
try opening it with the 64 bit version, or with either of the 4.1.4 versions if this one fails in the meantime. i used to have that problem too and never got it resolved, but 4.1.4 worked fine. it says to check the error log and it shows some message under the error box, but that probably won't help you.

**Comment by ElminsterAU** [comment]
You must have corrupt .bsa files. This is not a bug in xEdit. Please use the xEdit discord for support.

**Comment by IOcase** [comment]
[SOLVED] I have a very similar issue with SSEdit where it only successfully loads my full load order. Loading only partially causes this exact same error. I also don't find any errors in the message log except one. Googling it and it appears to be intentional and normal? I'm not sure what's going on and this is quite frustrating since I need to limit my plugins to less than 253 masters to run my scripts.

I reinstalled all of my mods, cleaned them, fixed wild edits, sorted LOOT, and now it works fine. I can load part of my load order just fine.
