### ISSUE TITLE
[Fo4] Get "Access is denied" When Trying to Save Changes to Any ESPs

### ISSUE THREAD

**Issue by JJ-Chambers** [TES5Edit/TES5Edit#1053]
**What is the version of xEdit you are using?**
Version 4.0.4

**Describe the bug**
Every time I try to save modifications to an ESP or create a new ESP with Fo4 edit I get this error

"[00:21] Error "EFCreateError": "Cannot create file "E:\SteamLibrary\steamapps\common\Fallout 4\Data\Synth Regeneration.esp.save.2022_11_08_19_20_26". Access is denied"

**To reproduce**
1. Make changes to an ESP or create a new ESP
2. Click the save button
3. Select any ESPs that were changed or created
4. Wait for error feedback in messages section

**Expected behavior**
I expected my ESP edits to be saved properly so I can modify an ESP.
![Capture](https://user-images.githubusercontent.com/48953561/200710563-d5b1ca2f-a544-402a-a797-b03cc9b418df.PNG)

**Screenshots**
Attached below.

**Additional context**
I tried running as administrator and I also tried reinstalling fo4edit, but neither of these solutions worked.

**Comment by ElminsterAU** [comment]
This is not an issue with xEdit. It shouldn't be reported here.

For support questions you should be using the xEdit Discord (see button in the top right corner).

Furthermore, the error is literally exactly telling you what the problem is.

The operating system does not allow the xEdit process to access (in this specific case, create or write to) the file.

The problem has nothing to do with xEdit. Make sure your computer is appropiatedly configured to allow xEdit to create/write to that file.
