### ISSUE TITLE
Remove Masters

### ISSUE THREAD

**Issue by DontBlnkBadWolf** [TES5Edit/TES5Edit#1061]
This is a Feature Request.

Allow the option to Remove Master(s) from plugins that are not the Main Master. i.e: Fallout4.esm, skyrim.esm....etc.

**Comment by VlitS** [comment]
The ability to edit the masterlist, and thus the ability to remove (or add) a master used to be in xEdit, but it was never intended to be used that way (it was basically just an oversight that the options were there), and were locked for very good reasons, explained below.

The "Clean Masters" option will safely remove any master that is not explicitly needed. Which means that, if there is any reference to or override from the master you are trying to remove, it will do nothing, but if you remove those (a combination of check for errors to look for "could not be resolved" errors, and the "Report Masters" script included with xEdit will let you track them down).

Directly removing a master from the masterlist (regardless of if it is the base game plugin or your own patch) does not remove things properly, even if the master you are removing would be removed by Clean Masters. This is because the internal IDs for records need to be updated (renumbered) once the master is removed*. Clean Masters does that, but editing the masterlist would not. Meaning that, unless you got very lucky, your plugin would become a broken mess if you just ripped out the master (same thing happens when you load a plugin with a non-ESM master [without CK Fixes, which changes this behavior]: the CK will destroy the plugin).  

*This is the same reason you can't just edit the list to add a master, you have to use "Add Masters"

**Comment by ElminsterAU** [comment]
Not seeing any issue reported here. The correct way to remove masters is explained above by @VlitS.
