### ISSUE TITLE
Deselecting item from the front of list for copy to selected record will also deselect from the end

### ISSUE THREAD

**Issue by Ghostwalker71** [TES5Edit/TES5Edit#1063]
**What is the version of xEdit you are using?**
Copy the first line from your xEdit messages window.
SSEEdit 4.0.4 (103758D4) starting session 2022-12-20 14:21:33

**Describe the bug**
Deselecting any number of items from the front of a list for copy to selected record will also deselect the same amount from the end of the record

**To reproduce**
1. Select a list of items (armor for instance) and compare
2. Choose a value to change in one of the records
3. right click the changed value and choose copy to select records
4. deselect any amount it items from the front of the list.
5. optional deselect any amount from the end of the list
6. notice how the amount from the front of the list is appended to the end of the list.

**Expected behavior**
Copied record should be applied to all selected items and not applied to any deselected items

**Screenshots**
![image](https://user-images.githubusercontent.com/1714240/208760656-ab040c45-00c4-478e-b77f-056e92389dab.png)
![image](https://user-images.githubusercontent.com/1714240/208760771-869c9c90-94fa-4fcb-ad2a-3d7be1b894ef.png)

**Additional context**
Notice by deselecting two items from the front of the list and three from the end of the list the result is five items from the end of the list are not updated.

**Comment by jbostrus** [comment]
PR for fixes pushed.

Issue was that during a loop, the index being used to set array data was using the loop counter instead of the selection counter. So it had 2 problems:

1. The array containing the column to copy to had invalid data based on what was de-selected
2. when the loop was completed and the final size of the array was set, it truncated the number of entries that were de-selected
