### ISSUE TITLE
xEdit truncated FormIDs do not match Creation Kit truncated ones. FE000xxx vs. FE001xxx

### ISSUE THREAD

**Issue by yustAnotherUser** [TES5Edit/TES5Edit#1074]
**What is the version of xEdit you are using?**
FO4Edit 4.1.4c EXTREMELY EXPERIMENTAL (5F018B15)

**Describe the bug**
The FormIDs created with xEdit when using the option "Compact FormIDs for ESL" are starting with FE000xxx whereas the FormIDs created by the Creation Kit (latest version & [latest CK Fixes](https://www.nexusmods.com/fallout4/mods/51165)) when using the option "Compact Active File FormIDs" are starting at FE001xxx!

**To reproduce**
load any esp thats not already ESL flagged in xEdit.
in the left pane right click on it select "Compact FormIDs for ESL"
see the IDs starting at FE000xxx
load any esp thats not already ESL flagged in Creation Kit and don't forget to set it as "Active File"!
under File click on "Compact Active File FormIDs"
Save it. Close Creation Kit.
Open it up with xEdit and see that the FormIDs all start at FE001xxx

**Expected behavior**
Obviously I want it to start at the same point the Creation Kit does because xEdit should do what the original developer tool does. I'm pretty sure that would be a good idea even if it never *seemed* to be a problem.

**Additional context**
Realized this by releasing this [mod](https://www.nexusmods.com/fallout4/mods/68572) because someone told me that LOOT complained about the file. See BUGS section on the mod page. Version 0.1 is a xEdit truncated one. Version 0.1.1 is the Creation Kit truncated one.  Fixed through [this](https://forums.nexusmods.com/index.php?/topic/11828438-loot-angry-at-my-esl/) hint. Fun Fact the file grew seven bytes in size after loading in CK, compacting and saving it.

**Comment by jbostrus** [comment]
The 000 or 001 in your example, is the light module index. Just like 01xxxxxx, 02xxxxxx, ABxxxxxx are the full module indexes. So the 3 digits after the FE indicate which light module index the plugin is currently in. So if xEdit is showing it as FE001 that is because there is another light plugin loaded in the current view at that time.

**Comment by yustAnotherUser** [comment]
Oh yeah you are right, silly me.. never realized that even though it is so obvious. So why did LOOT complain then? The method with the Creation Kit did actually changed one single FormID [see picture](https://ibb.co/S5NmpMQ). Funnily the Creation Kit didn't pick the first free slot which would have been number 4 instead it gave it 8 but it changed it from 738 to 8 and LOOT stopped complaining. So that 738 is according to LOOT outside a valid range which breaks any save beyond repair. The question is why did it got this number assigned in the first place as the esp was already marked as an esl with xEdit when I loaded it into the creation kit and placed this power connector.... why did the Creation Kit assign a number outside the valid range? Is the ESL tagging from xEdit not enough for the Creation Kit to recognize it properly or is the Creation Kit just bugged beyond fixable and doesn't care in the moment of placing new items because the workflow says that you have to compact the FormIDs *everytime* as a last step before saving.

So maybe a sanity check if all FormIDs are still within valid range in a ESL flagged esp when saving/exiting xEdit would be a nice thing?

**Comment by jbostrus** [comment]
738 is within the valid range. The problem is that the FormID isn't actually 738. If you removed the ESL flag and saved the file, then reloaded to see the full slot form ID you'll see what it really is. **That** is why LOOT was complaining.

xEdit does check that. It checks when you set the ESL flag and try to save. I don't recall what all checking it does if it already has the ESL flag. But I'm fairly sure it checks then too, as long as there was a change that makes it actually re-write the file.

The issue likely occurred because you had already set the ESL flag. Then opened it in CK and edited it with the ESL flag still present on the plugin. That workflow is problematic. You should remove the flag before editing. Then re-flag afterwards. This ensures that things like this doesn't happen because xEdit won't let you save with an invalid ID. CK will.

I would posit that you opened a an already ESL flagged plugin, made a change and saved. When it saved it had a FormID that was outside the 0x800-FFF range that ESL supports. Since CK doesn't actually care about the ESL flag when loading a file it will happily save a bad file leaving the ESL flag and an internal FormID outside the valid range, where that state is invalid. So the error that was reported is because when CK saved it, the internal ID it saved with was something like xx002047. If you loaded it xEdit would see the ESL flag and show it as xxnnn047 but when re-saving would complain about an invalid ID. Though maybe only if you made a change that made it look at it.

**Comment by jbostrus** [comment]
Erm my bad I just noticed your thing is for Fallout 4. So if the plugin header version is 1.0 the valid range is 0x001-FFF. If the version is 0.95 then it starts at 0x800 like Skyrim.

**Comment by yustAnotherUser** [comment]
You are absolutely correct in what I did. xEdit indeed stopped me from saving if i change anything in the file and even tells me in the error message whats it's original ID is and that this is out of range. I also removed the ESL flag by unchecking it in the header options, saved it, reloaded it, and it's funnily enough still 738 but it seems its full ID is 1738. [Screenshot](https://ibb.co/SQGNfPN). After compacting the FormIDs again it reassigned the connector the same number as the Creation Kit did. It choose number 8 and not 4. So everything is fine. Thanks for taking the time and clarification. Much appreciated.

**Comment by jbostrus** [comment]
Something else in your plugin is using 4 then. Otherwise it would use that.

**Comment by yustAnotherUser** [comment]
Indeed xEdit also gives me this information on loading such a bad ESL plugin...

> [00:06] Background Loader: <Error: [REFR:FE000738] (places WorkshopPowerConnectorWall01 "Power Connector" [ACTI:000C01C6] in GRUP Cell Persistent Children of [CELL:00018AA2] (in Commonwealth "Commonwealth" [WRLD:0000003C]) at -10,9) has invalid ObjectID 001738 for a light module. You will not be able to save this file with ESL flag active.>

the only problem is that this message completely gets lost within all the other thousand of lines.. So I guess an extra tab besides "Messages" called "Errors" would be super viable. I never saw that and I loaded the plugin quite often. I just saw it right know because I specifically looked after it because you mentioned xEdit checks for that and yes it does but it doesn't tell you appropriately...
