### ISSUE TITLE
Assertion error with a specific plugin

### ISSUE THREAD

**Issue by VishVadeva50** [TES5Edit/TES5Edit#1083]
**What is the version of xEdit you are using?**
SSEEdit 4.0.4c (264F2054) starting session 2023-04-02 03:47:50

**Describe the bug**
The Unofficial Skyrim SE Fixes.esp module from [this](https://www.nexusmods.com/skyrimspecialedition/mods/87247) mod causes an assertion failed error in xEdit 4.0.4c (merged version, esp and esp-fe both have the issue). The error is not consistent, sometimes the plugin can load for a few times in a row then it errors for the next 10 times. So any testing will require multiple runs to replicate.

Tested with 4.0.4 and 4.0.4b, both do not have this issue after about 20 attempts. Here are the setups i tested on 4.0.4c:
No cache present for mod and its masters + -DontCacheSave = no error
Cache present = no error
No cache present for the mod, but present for its masters + -DontCacheSave = error on the 2nd load

**To reproduce**
1. Cache all of the mod's masters
2. Run xEdit with -DontCacheSave
3. An assertion error will appear after a few attempts or more

**Expected behavior**
The mod should load normally without an error

**Additional context**
Windows 11, clean install of xEdit 4.0.4c from the discord server, tested on 2 different windows installs and on multiple installs of the same xEdit version, logs are attached.
[xEditException.log](https://github.com/TES5Edit/TES5Edit/files/11131088/xEditException.log)
[SSEEdit_log.txt](https://github.com/TES5Edit/TES5Edit/files/11131089/SSEEdit_log.txt)

**Comment by ElminsterAU** [comment]
Most likely cause is that you are clicking around while the loader is still running.

**Comment by VishVadeva50** [comment]
I managed to get the error and did nothing after loading the module

**Comment by ElminsterAU** [comment]
The file has missing PNAM entries in INFO records, attempting to fill these in while multi-threaded reference building is going on can cause race conditions and concurrent access to changing data structures from different threads.

**Comment by VishVadeva50** [comment]
By missing PNAM you mean PNAM overrides to Skyrim.esm that set it a null reference? I see 3 of those in the plugin, but there is also an ITM that has PNAM null in both

**Comment by ElminsterAU** [comment]
PNAM define the order of INFO records, in the absece of PNAM subrecords, the order is only implicitly given by the order in which the INFO records occur in the file, which is very fragile. xEdit will add and fill in these missing PNAM subrecords when the order of the INFO records is established, so you aren't going to see them missing because xEdit already filled them in.

In the experts tab in the options this filling in behaviour can be turned off. But these PNAM really shouldn't be missing in the first place.

You should one time load only that file (and it's required masters) successfully with the PNAM setting taking place, then mark the whole file as modified and save.

After that it should no longer need to add the PNAMs on load.

**Comment by VishVadeva50** [comment]
Thank you
