### ISSUE TITLE
Can't add weapon to leveled list

### ISSUE THREAD

**Issue by AldebaraanMKII** [TES5Edit/TES5Edit#1086]
**What is the version of xEdit you are using?**
FO4Edit 4.0.4 (5B1C2C51)

**Describe the bug**
Whenever i try to add "WPN_MCXSPEAR "SIG MCX Spear" [WEAP:xx000001]" from https://www.nexusmods.com/fallout4/mods/62283?tab=files, the record changes into "DoorMarker [STAT:00000001]". This doesn't happen with the next weapon in line "WPN_MCXSPEAR_BH "Bravo Hotel" [WEAP:xx000FFF]"
Also happens when adding the gun from https://www.nexusmods.com/fallout4/mods/62595?tab=files

**To reproduce**
1. Open BH_MCX_Spear.esp on FO4Edit
2. Try adding WPN_MCXSPEAR "SIG MCX Spear" [WEAP:xx000001] to any item leveled list inside another plugin

**Expected behavior**
That the weapon gets added just like any other

**Screenshots**
Here's a video of it: https://files.catbox.moe/a06prb.mkv

**Comment by jbostrus** [comment]
The record gets shifted to the DoorMarker because the file you copied the reference into has HEDR version 0.95 in the file header. For FormIDs below 0x800 the HEDR must be 1.0 or they are treated as overrides of hard coded IDs in the game exe/esm.

The options are either

1. Renumber the forms from your weapon plugin to be in the range 0x800-0xFFF so when they're added as references into a 0.95 plugin they work.
2. Change the HEDR of the plugin you're adding the reference to to be 1.0 instead of 0.95.

**Comment by AldebaraanMKII** [comment]
> 

https://imgur.com/a/mi8U5z5
problem is that the HEDR is already 1.0

**Comment by AldebaraanMKII** [comment]
https://imgur.com/a/mi8U5z5

**Comment by AldebaraanMKII** [comment]
> The record gets shifted to the DoorMarker because the file you copied the reference into has HEDR version 0.95 in the file header. For FormIDs below 0x800 the HEDR must be 1.0 or they are treated as overrides of hard coded IDs in the game exe/esm.
> 
> The options are either
> 
>     1. Renumber the forms from your weapon plugin to be in the range 0x800-0xFFF so when they're added as references into a 0.95 plugin they work.
> 
>     2. Change the HEDR of the plugin you're adding the reference to to be 1.0 instead of 0.95.

Changed the HEDR and everything work now. Thanks.
