### ISSUE TITLE
Clean Masters feature is not working in some cases and can break esp.

### ISSUE THREAD

**Issue by ir4ne** [TES5Edit/TES5Edit#1099]
TES4Edit 4.0.3 (1CDF3AC7)

**Description**

When trying to remove mod A from the list of masters of mod B via "Clean Masters (= Remove all unused masters)", the master is successfully removed from the list, but when closing and reopening TES4Edit it reappears, and some entries of mod B become marked as overridden entries from mod A, although they were not previously. It is not entirely clear under what conditions this occurs. Also, the master is not removed at all if there is PlayerREF usage in mod B scripts for some reason. 

**To reproduce**

1. Open attached archive,  copy .esp files from it into yours Oblivion/Data directory.
2. Open TES4Edit, right click on IICHandlers_AGFM.esp, select "Clean Masters (= Remove all unused masters)" option. See that ActionGraphFramework.esp is still in the masters list. Also see that none of the entries from ActionGraphFramework.esp are marked as overridden entries in IICHandlers_AGFM.esp.
3. Close TES4Edit, open Construction Set, open IICHandlers_AGFM.esp, open "IicSlowMoEffectOn" script and comment/delete the following lines in it: 
```
if attacker != PlayerRef
    return
endIf
```
Save and recompile.
4. Open TES4Edit again, right click on IICHandlers_AGFM.esp, select "Clean Masters (= Remove all unused masters)" option. See that ActionGraphFramework.esp succesfully removed from IICHandlers_AGFM.esp masters list. Save changes.
5. Close TES4Edit, reopen it and select IICHandlers_AGFM.esp. See that ActionGraphFramework.esp is in masters list again and some entries of mod IICHandlers_AGFM.esp are now marked as overridden entries from ActionGraphFramework.esp.

**Expected behavior**
1. Using PlayerREF in IICHandlers_AGFM.esp scripts shouldn't prevent ActionGraphFramework.esp from being deleted from its masters list.
2. After successfully deleting  ActionGraphFramework.esp from IICHandlers_AGFM.esp masters list its expected to stay that way after saving. Entries that wasn't previously marked as overridden are expected to stay that way.

**Screenshots**
Initial state:
![image](https://github.com/TES5Edit/TES5Edit/assets/118213859/8316f19d-0b02-4dfd-b4de-4ae05900881f)
Master successfully removed:
![image](https://github.com/TES5Edit/TES5Edit/assets/118213859/73bc4067-8cb7-40c5-9046-212a685f65c2)
Master appears again with entries marked as overridden which previously wasn't:
![image](https://github.com/TES5Edit/TES5Edit/assets/118213859/b35f97ac-1092-4c03-9461-35a2b94bd38a)

[TES4EditIssue.zip](https://github.com/TES5Edit/TES5Edit/files/12386804/TES4EditIssue.zip)

**Comment by VlitS** [comment]
First issue is the same as the one reported here: https://github.com/TES5Edit/TES5Edit/issues/965. This spawned from a similar situation (the base game master was the only master and the one being re-added), but the fix mentioned in that issue should resolve. Try grabbing xEdit 4.0.4c from the #xedit-builds channel on the discord (discord link in the top right of xEdit). 

~~Based on the time of that commit, it should be included in that incremental update.~~ Edit: Nevermind, it was included in the 4.0.4 release that was posted to the nexus as well, though it is still not a bad idea to grab 4.0.4c. 


I believe the issue with the player ref is due to the fact that the player ref is 00000014 and is hardcoded in the Tes4 exe (at least it is done that way in later games, don't have oblivion currently installed). Since you don't have that ESM file loaded, it sees that the formID prefix for the master (ActionGraphFramework.esp) is 00, and since the playerRef also has 00, it treats it as being from that master? The playerRef is weird, it sort of both is and isn't a placed NPC record. 

If you want to discuss this one on the discord instead of continuing it here for the playerRef issue, best channel would be #feedback.

**Comment by ElminsterAU** [comment]
xEdit is not designed to work without having the game master loaded. Ensure you always load the game master as well as the modules you are working on.

**Comment by ElminsterAU** [comment]
4.1.4r and later ensure that the game master is always loaded, even if it's not the master of any file that's explicitly being loaded
