### ISSUE TITLE
issues about editing perks

### ISSUE THREAD

**Issue by 132793** [TES5Edit/TES5Edit#1100]
3.13 and 4.02
i am trying to edit perks on ordinator, perks of skyrim. Yesterday, everything worked fine. However, today, it seems that xedit failed to write content into the esp. To be more specific, When i try to delete some features of a perk, it could really achieves that, and the result can be reflected in the game. However, If i try to add some features in a perk, it does not work at all or only partially work. Although xedit shows that my editing is saved in the esp, it does not work properly in the game. For example, i am trying to set two effects(entry point) in a perk. the first effect is about applying hit spell to the enemy through a melee attack, and the second effect is about setting my critical damage chance to 100 if am attacking an enemy with the effect caused by the hit spell. If i add the hit spell effect first into the perk, it will work properly but the second entry point does not work. if i add the critical damage chance effect first(for testing, i delete the condition which requires the hit spell), this entry point works well in the game while the hit spell entry point does not work. Things get worse when i try to skip to that problem and edit another perk. all entry points i add in another perk do not work while it could delete the initial entry point..........i am totally confused by such abnormal and unexpected phenomenons. i hope someone could help me solve this problem.
Plus, i am using MO to launch xedit.

**Comment by ElminsterAU** [comment]
xEdit does not implement all the extremely complex handholding that would be required to ensure that you are creating valid data structures when adding data to perks. It's up to you to actually add all the parts correctly so that they work together to result in a valid overall structure. 

xEdit does correctly save exactly what it showed you on screen about the changes you made. But you are responsible for actually making changes which are all logically consistent and correct in multiple different elements and their relationships with each other.

Deleting things is very easy. Adding things requires you to have an in-depth understanding of how the game code works.

I would strongly recommend that any non-trivial addition to perks is made in CK.
