### ISSUE TITLE
path issue

### ISSUE THREAD

**Issue by whitevamp** [TES5Edit/TES5Edit#1200]
yes i have looked and I did see this issue/ question https://github.com/TES5Edit/TES5Edit/issues/1087#issuecomment-1567306767
but I am using MO2 and all this dose is try to open up the *.ini files out side of MO2 that don't exist. is there any way around this, with out making the folder its looking for, and making hard links to the files its trying to find?

**Comment by jbostrus** [comment]
The official standpoint is that xEdit works as described when executing normally. If there's some issue about MO2 not finding things because of whatever reason. That's a thing you need to discuss with the MO2 people to get them to fix it. Since it sounds like it's a VFS issue where running xEdit inside MO2 cannot find something because the VFS is confused about what to load because it doesn't exist outside MO2. This is again, an MO2 issue not xEdit.
