### ISSUE TITLE
File sizes differ in recent 4.1.5.Experimental release

### ISSUE THREAD

**Issue by dizietsma** [TES5Edit/TES5Edit#1261]
I've always used xedit as just that, xedit.exe with the argument for the relevant game -SSE etc.  I know that renaming the xedit.exe is another way to get xedit to edit the relevant game.  Accordingly I would have imagined that renamed xedit.exe files would have the same sizes, but the ones in the release don't.
So are there differences that mean I need to use the particular file for each game?  Currently I have one install of xedit and just run it from my mod manager with the appropriate command line.
Can I just use any of the included exes in the 4.1.5 release and rename it to xedit?

diziet

**Comment by jbostrus** [comment]
I'm not sure exactly which files you're referring to as having different sizes. If you mean the SSEEdit, FO4Edit, and SF1Edit from the nexus archives. Then yes they'll be different sizes because they have different icons. But renaming any of those exe's or using the desired game mode command line argument will result in it running the correct game mode. Just having whatever icon was embedded in the exe file. The exe in the GitHub releases and the Discord builds channels have the standard red Skyrim icon.

**Comment by dizietsma** [comment]
Icons in the files! I feel like such a numpty, that never occurred to me. Thankyou for clearing that up:)

diziet
