### ISSUE TITLE
[EJvInterpreterError] : Undeclared Identifier 'GetLoadOrder'

### ISSUE THREAD

**Issue by jayrthrush2** [TES5Edit/TES5Edit#1294]
**What is the version of xEdit you are using?**
SSEEdit 4.1.5c EXTREMELY EXPERIMENTAL (AACDCC19) starting session 2024-02-14 22:44:55

**Describe the bug**
Exception in unit  line -1: [EJvInterpreterError] Error in unit 'FindPotentialESL' on line 69 : Undeclared Identifier 'GetLoadOrder'

**To reproduce**
1. Right-click in left pane
2. select "Apply Script"
3. select the "Find ESP plugins which could be turned into ESL" script in the dropdown menu
4. Click "Run"
5. wait for error

**Expected behavior**
Should list plugins that can be converted to esl and what needs to be done to do so.

**Screenshots**

**Additional context**
Works Properly in 4.1.5b

[SSEEdit_log.txt](https://github.com/TES5Edit/TES5Edit/files/14291353/SSEEdit_log.txt)
[xEditException.log](https://github.com/TES5Edit/TES5Edit/files/14291354/xEditException.log)

**Comment by fireundubh** [comment]
In 4.1.5c:

- `FileByLoadOrder` was replaced with `FileByLoadOrderFileID`.
- `GetLoadOrder` was replaced with `GetLoadOrderFileID`.

~~The replaced functions have been broken since the introduction of ESLs (around 5 years).~~ All scripts using these functions, including bundled scripts - xEdit core does not use them at all - need to be updated.

edit - 14 Feb 2024: There was a miscommunication about the replaced functions. We'll be restoring those functions in a future version; however, the `*FileID` functions are more correctly used for working with Form IDs and will remain exposed.

**Comment by MattStarwalker** [comment]
Hi
I am wondering if there is a way to download 4.1.5b while we wait? I am trying to use the RAB smash splitter scripts and they make use of GetLoadOrder. I can't see how else to get these scripts working.

**Comment by jbostrus** [comment]
We've already done a 4.1.5d build on Discord in the #xedit-builds channel. But 4.1.5b is also available there.

**Comment by MattStarwalker** [comment]
> We've already done a 4.1.5d build on Discord in the #xedit-builds channel. But 4.1.5b is also available there.

Thank you. 4.1.5d gets past the error!
But the script I am trying to use still doesn't work, it has a type mismatch, so I guess that's going to be the end :(
