### ISSUE TITLE
FO4Edit hijacks other xEdits

### ISSUE THREAD

**Issue by festro** [TES5Edit/TES5Edit#1346]
**What is the version of xEdit you are using?**
xEdit.4.1.5f
Copy the first line from your xEdit messages window.
FO4Edit 4.1.5f x64 (7C57FA01) starting session 2024-05-26 17:42:17
**Describe the bug**
I was previously using FO4Edit to clean mods in my collection that went just fine but now
I am opening xTESEdit to edit Skyrim to do the same and FO4Edit hijacks it, fo4edit also hijacks any of the other xedit executables.
I've even tried deleting the FO4Edit executable and the xedits still open up as if I've opened FO4Edit.

**To reproduce**
(to the best of my knowledge)
1. Use FO4Edit to clean mods (particularly quickautoclean)
2. quit FO4Edit
3. Try running any of the other XEdit executables (xTESEdit, SFEdit)
4. FO4Edit should run in it's place

**Expected behavior**
The XTESEdit to be run rather than FO4Edit.

**Screenshots**
![Screenshot 2024-05-26 175719](https://github.com/TES5Edit/TES5Edit/assets/2665113/e5900acf-ced0-464a-b1f0-cc03af51c4c2)

**Additional context**

**Comment by dsp2oo3** [comment]
The executables supplied on Github you've mentioned **aren't actually named properly**, that's why they load in FO4Edit mode by default. The names should be these:

For Starfield: SF**1**Edit.exe
For Skyrim LE: TES**5**Edit.exe
For Skyrim SE: **SSE**Edit.exe
For Oblivion: TES**4**Edit.exe
For Morrowind: TES**3**Edit.exe (will throw an error as it's not currently supported)

Alternatively, you can keep just one executable and pass the proper editor mode as a launch parameter, either in a batch file or a program's shortcut. Refer to program's manual for further details.

**Comment by festro** [comment]
Thanks I'll give it a try and post the results.

**Comment by festro** [comment]
Thanks SSEEdit worked. Hopefully this gets fixed, was wracking my head over it.

**Comment by ElminsterAU** [comment]
There is nothing to fix. Everything is WAD. This issue is purely a case of PEBKAC.
