### ISSUE TITLE
Empty records in the Synthesis.esp 

### ISSUE THREAD

**Issue by MariusKlug** [TES5Edit/TES5Edit#1383]
**What is the version of xEdit you are using?**
TES5VREdit 4.1.5f (094C4648) starting session 2024-09-20 16:36:26

**Describe the bug**
My Synthesis.esp has empty Actor Value Information records as displayed when looking at Adamant.esp, but not when looking at Synthesis.esp itself. Also when CTRL-clicking on that Synthesis.esp at the top, it refers to the wrong reference, a crate container within Synthesis.esp. Note that the game behaves correctly, no crash or issue with the empty actor value information of the perk trees, so I suspect it is a display issue.

**To reproduce**
1. Go to Adamant.esp
2. Click on Actor Value Information
5. CTRL-click on the Synthesis.esp at the top right of the empty records
6. Get wrongly referred

**Expected behavior**
No empty records

**Screenshots**
![grafik](https://github.com/user-attachments/assets/43d44899-9573-41b4-844a-b3bf29f5777e)
![grafik](https://github.com/user-attachments/assets/4f200428-e4bf-4d6a-980e-7e08c873dbc6)

**Additional context**
This is Skyrim VR with the ESL support mod.

**Comment by jbostrus** [comment]
Short answer here is that your Synthesis patch is creating a record with a FormID that would be a hard coded override, and it is of a different type than the one xEdit thinks it's trying to override.

The reason xEdi thinks it's an override and not a new record is that your Synthesis patch is using FormIDs in the low < 0x800 range. For the older game EXEs (including VR), these are treated by the game as hard coded record overrides. xEdit *used* to incorrectly show these types of records as new in certain situations. The newer versions of xEdit now use the HEDR version 1.71 or 1.70 to identify how it displays them in accordance with how the game should treat them.

This means that using the latest SSE (not VR) which now uses version 1.71 will now use them as new records and not overrides. When xEdit sees the HEDR version 1.70 it assumes you're on an older game which will treat it as an override. Which in your case since you're on VR this would be the case.

**Comment by MariusKlug** [comment]
Thank you for your quick answer! I was on an older version of Synthesis, updated now (v0.3.0), and the issue is gone.
