### ISSUE TITLE
FNVEdit shows conflict for injected records instead override

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TES5Edit/TES5Edit#183]
```
What steps will reproduce the problem?
1. Please download the attached files. Load them in FNVEdit as:
   FalloutNV.esm
   test1.esp
   test2.esp
2. open the weapon 001735E5. Observe the red/fuchsia colors that highlight a 
conflict.

What is the expected output?
No conflict, just an override. Yellow background and Green foreground.

What do you see instead?
A conflict. The upper index record has red foreground, meaning conflict looser.

What version of the product are you using? On what operating system?
r1859

Please provide any additional information below.
The same scenario works as intended in TES5Edit. So FNVEdit considers injected 
records in a special way.
The records are taken from "TribalPack.esm" and "Grenade Hotkey", but I 
isolated them for simplicity.
```

Original issue reported on code.google.com by `clampa...@gmail.com` on 16 Dec 2014 at 5:57

Attachments:
- [Test.7z](https://storage.googleapis.com/google-code-attachments/skyrim-plugin-decoding-project/issue-183/comment-0/Test.7z)
- [Conflict.png](https://storage.googleapis.com/google-code-attachments/skyrim-plugin-decoding-project/issue-183/comment-0/Conflict.png)

**Comment by eFrysTon** [comment]
This is not a bug. 
It's very much intentional that any time there are two or more values for an element and the record is injected, it is classified as a critical conflict.
Without a true master, it's impossible to say if the two different versions of the record are even for the "same" record, if it's just that two different people ended up injecting two different records using the same FormID.
This will not be changed.
