### ISSUE TITLE
Request: Add zopfli or 7-zip compression algorithm

### ISSUE THREAD

**Issue by 0siribix** [TES5Edit/TES5Edit#202]
zopfli and 7-zip compression algorithms are superior to zlib's. They produce zlib compliant streams which means zlib can decode them yet the compressed data is smaller.

**Comment by zilav** [comment]
What's the point? The only records that could take advantage of that are LAND and NAVM due to their size, and only large landscape mods contain them in enough quantity to justify any changes, and I can count such mods using one hand fingers literally. Even then it will probably reduce their size by 500k on average. Absolutely not worth it. Besides the purpose of xEdit is to mimic the behaviour of official editors and create indentical plugins, not to improve storage format. Right now it uses the same zlib version as Bethesda, and it proved to be reliable for all games.

**Comment by SamB** [comment]
While it certainly doesn't sound like it would buy you much, I have trouble believing that Bethesda managed to find a version of zlib broken enough to choke on streams produced using the 7-zip or zopfli implementation of DEFLATE: compatibility with existing decoders (mostly zlib) is the primary design requirement for both, after all. (Zopfli doesn't even *support* decompression.)

The fact that zopfli is supposed to be 10-1000 times as slow is far more likely to be a problem; however, an [AdvanceCOMP](https://en.wikipedia.org/wiki/AdvanceCOMP)-like mode for TES5Edit might still be interesting, if only in an experimental^2 branch, to see how much it could shrink that handful of mods. (The [AdvanceCOMP code](https://github.com/amadvance/advancecomp) would likely be helpful for such an experiment.)

**Comment by zilav** [comment]
If you find at least a single valid reason for that, we could try (or even test yourself). I don't have too much free time for experiments right now.

**Comment by 0siribix** [comment]
I would want to try recompressing the official ESMs and (even though it's taboo) also Skyrim.esm. If you could provide me with an easy way to extract and reinsert compressable parts of an ESP/ESM, I could compress those parts manually and share my findings (time, size savings, etc).
