### ISSUE TITLE
TES5Edit - Partial read of quest aliases

### ISSUE THREAD

**Issue by PlagueHush** [TES5Edit/TES5Edit#204]
Dialog Topic records that reference quest aliases are only verified by TES5Edit from 0 to 13, anything higher is marked as "Quest alias not found".

This can be replicated by downloading the Hearthfire patch from "MFVM - More Follower Voices Mod Plus Khajiit Marriage" (http://www.nexusmods.com/skyrim/mods/36913/?) where I first noticed this issue, and running a Check For Errors.

Alternatively, searching the Hearthfire.esm for FormID xx003DFC and copying as override into a new esp will show the working quest alias links switch to errors in the new esp, but only those numbered over 13, which remain unlisted if you drop down the list of quest aliases. Screenshot attached.

https://dl.dropboxusercontent.com/u/2028885/Screenshot%202015-10-12%2001.08.06.png

**Comment by zilav** [comment]
The quest record RelationshipMarriageFIN [QUST:00021382] originates from Skyrim.esm, and that alias is added in Hearthfires overriding it. Right now alias resolver works as following:
- when alias is referenced in the same plugin with the quest record, then quest record that from plugin is used. That's why you see alias 016 when viewing in Hearthfiles.esm
- when alias is referenced from another plugin, in this case from overriding plugin, then quest master record is used. Master record is in Skyrim.esm and it doesn't have alias 16 and few others.

Quest stages resolver also work the same. I guess we could change that behaviour to always use the latest quest override record, but it will also have downsides. For example you have a plugin that references truly invalid alias, and then some later loaded plugin adds alias with the same number but completely different meaning. So TES5Edit will treat that alias as valid while it is clearly an error.

**Comment by PlagueHush** [comment]
Ahh I see. Thanks for the quick reply!

I understand why the decision was made, to avoid potential mod conflicts, but it does seem to be contrary to a lot of the way T5E handles things elsewhere. As users we get very used to the fact that "last record wins", so I'm not sure this is helping understanding being this way around. It confused me after all!

I also leaves T5E reporting errors in mods that do not legitimately have any. The mods work perfectly and check out in the CK, but T5E is insistent there is a conflict. I suppose a workaround might be to copy the actual quest into the same esp, but for mods that are simply attempting to add a couple of lines of conditional idle dialog, this seems hugely overkill and would probably cause more trouble that it's worth?

I for one would much prefer to see this work on the "last record wins" principle, and see T5E reporting less false errors.

**Comment by zilav** [comment]
Uploaded updated version on afkmods, please check it.

**Comment by Arthmoor** [comment]
I'd suggest caution here since two different mods can both add an alias to a quest with the same ID and if xEdit sees this and assumes "last record wins" but doesn't show this as a conflict, chaos will ensue.

**Comment by PlagueHush** [comment]
The new version is working entirely as expected!

I understand there is a potential risk with clashes between mods that adds the same alias ID to the same quest, but I don't think this is unexpected within the context of the way we understand T5E to work, personally.

Equally, as things stand prior to this change, mods that do make changes to the same quests will overwrite each other anyway, and are well understood to cause issues when it happens (dialogfollower being the widest known culprit). This way around I think at least prevents false positives, and error detection in mods that don't actually have any.

Really pleased with the results and thanks for the speedy work to address the request Zilav!

**Comment by zilav** [comment]
Yes "check for errors" for quest stages and aliases will now depend on the plugins loaded in xEdit, similar to cleaning. So for the best result only plugin to be checked and it's masters should be loaded. I can always make this optional if something goes wrong. Leaving this issue opened for now.

**Comment by Hugues92** [comment]
It should be tested but I am pretty sure the modified xEdit would be what the game would do itself: Use the winning override. 
Worst case, if the overriding property is not  of a compatible type with the winning script, it's likely the quest would error out at runtime.

**Comment by zilav** [comment]
No issues reported so far, assuming it works fine for everyobe.
