### ISSUE TITLE
FNVMasterUpdate.exe

### ISSUE THREAD

**Issue by Hazado** [TES5Edit/TES5Edit#205]
Issue: XEdit does not load the plugins in the correct order after using FNVMasterUpdate.exe on some of the plugins.

I used FNVMasterUpdate.exe on a few ESP, after loading them inside FNVEdit 3.1.2, I noticed the load order did not match the plugin order I had setup inside Mod Organizer.

Specifically, More Perks.esm at 2F was listed at 2A inside FNVEdit.

![mod organizer](https://cloud.githubusercontent.com/assets/416114/10672078/a80ec52c-78a2-11e5-9686-86bcb6d3cce1.png)
![fnvedit](https://cloud.githubusercontent.com/assets/416114/10672079/a8100ee6-78a2-11e5-98f6-9d64a52c51ee.png)

**Comment by zilav** [comment]
For fallouts *.esm files come first, then *.esp, been so since the first FNVEdit version.
MasterUpdate/MasterRestore is an outdated technique from the early days of modding which should not be used nowadays.

**Comment by Sharlikran** [comment]
Also another thing to remember that LOOT, BOSS, NMM, and Wrye Bash all sort ESM files first.  Once a file has the ESM flag set, regardless of the .esp extension, it will sort first in the list.  In fact Wrye Bash has routines to update that the instant it happens.  It is expected and all utilities regardless of whether or not MO does that should be doing that. 

To further illustrate this is expected behavior, take MO out of the equation.  Once you run MasterUpdate/MasterRestore and then BOSS or LOOT it will not only sort them first but change the dates of the files so that the .esp files are among the ESM files.  If you were to run Fallout NV it would handle the .esp files as masters as is usually the intention for false flagged files.

I use different methods but normally when I set the ESM flag temporarily it's because I am making an esp file a master of another file. I know what you are describing and I know that once I am done with the mod that I have to turn off the ESM flag and sort with LOOT before I play.  It's just how it is.
