### ISSUE TITLE
FO4Edit: Spaces and special chars in EDID

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#237]
Can you restrict the allowed characters for EDID strings to alphanumeric characters? Although there doesn't seem to be a problem with non-alphanumeric characters like spaces and dashes, as the game likely cares about only Form IDs, there are no records whose EDIDs have spaces, dashes, or other non-alphanumeric characters, so I think xEdit should enforce that pattern as a rule.

**Comment by zilav** [comment]
Game doesn't use EditorIDs, only FormIDs. So it is only a matter official editor formatting. While it can be done, I don't see any reason too. xEdit first appeared in 2008 it has never beem a problem since then, user must have responsibility and think about what they are editing and how. Much more harm could be done by removing subrecords, entering abnormally large values in integer and float fields, etc. We can't control it.

**Comment by fireundubh** [comment]
> While it can be done, I don't see any reason too.

It's so trivial to implement, I don't see any reason why you *wouldn't* though. The user *should* be responsible, yes, I agree, but you know that's idealistic. I can't open the UI sources without XE crying about virtual trees and corrupting the project; otherwise, I'd just write the code myself and give it to you.

**Comment by zilav** [comment]
It is not trivial. The changes must be made in core modules to either support formatting callbacks for string types, or hardcoding strings parsing for elements with EDID signatures. UI has nothing to do with it.
