### ISSUE TITLE
xEdit Feature Request: Columnized Referenced By Tab

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#243]
I've always wanted the Referenced By tab to use more than a single column for record data. Since you added the Signature column, I thought you could expand that further.

### Screenshot

![Screenshot](http://i.imgur.com/wz8QTpx.png)

I wanted to separate CELL and WRLD into two columns, but I don't think there's an easy way to separate them or get the containing worldspace from a reference.

It'd also be nice to be able to sort by more than one column, in which case the default sort order should be `File > Signature > Form ID`.

By the way, the Referenced By tab doesn't inherit the Viewer font settings.

### Code

```delphi
with lvReferencedBy.Items.Add do begin
  rbItem := ActiveMaster.ReferencedBy[i];
  {0} Caption := rbItem._File.Name;
  {1} SubItems.Add(rbItem.Signature);
  {2} SubItems.Add(IntToHex(rbItem.FixedFormID, 8));
  {3} SubItems.Add(rbItem.EditorID);
  if InStringList(rbItem.Signature, 'REFR,ACHR,PGRE,PHZD,PMIS') then
  {4} SubItems.Add(rbItem.ElementByName['Cell'].EditValue)
  else
  {4} SubItems.Add('');
  Data := Pointer(ActiveMaster.ReferencedBy[i]);
end;
```

InStringList() is just a more convenient way to write `or` statements for string comparisons.

```delphi
function TfrmMain.InStringList(const x, y: String): Boolean;
var
	idx: Integer;
	l: TStringList;
begin
	l := TStringList.Create;
	l.DelimitedText := y;
	idx := l.IndexOf(x);
	l.Free;
	Result := (idx > -1);
end;
```

**Comment by zilav** [comment]
The problem here is "I wanted...". Yes I want something too, and sure that other people also would want features specific to thier modding practices. Stacking up additional columns for any imaginable value is not the best approach. So you added Cell, but then someone can ask - why don't you put Cell's X and Y into separated columns, that would make much more sense since 95% of exterior cells don't have EditorID, why don't you add "Enable parent" column, a ref's scale column, and on and on.
No way to make everyone happy. I added Signature since it does make sense actually to sort all referencing records by type, that's useful in general for anyone. But long cell's info string, worldspace? Not so sure, for me it is completely useless. That information doesn't help me in any way. But it does help you obviously.
I'd rather see you making a hotkeyed script that will open a window with the same ListView of references, with options to set up columns where user can specify path to any element he wants to see, options will be stored in ini file, there will be sorting by several columns, export to different formats, right click popup menu with actions like copying selected records to other plugins, etc. THAT will be useful for everyone, I will happily use it too. And it's extensible.

"Or" checks are used because they are faster since compiler will stop checks after the first match. If you want to search in a string of references, then better use Pos().

You can get worldspace out of a cell the same way you get a cell out reference - EditValue of the first element.

**Comment by fireundubh** [comment]
> The problem here is "I wanted...". Yes I want something too, and sure that other people also would want features specific to thier modding practices.

Kind of the point of a feature request. You should post your feature/script requests.

> So you added Cell

The vast majority of the items in the Referenced By tab are REFRs. It makes sense to optimize for the most common use case.

> No way to make everyone happy.

A single column for the full path to a reference that doesn't sort well at all doesn't make anyone happy and falls under your "completely useless" category. There are chunks of information in there that, when sortable, would be useful to at least *some* people.

**Comment by zilav** [comment]
I don't post request, who will fulfil them? :)
The vast majority depends on the type of record. Imagespaces, keywords, weathers, lighting templates, cells, etc. would barely have any REFRs at all. Looks like you personally prefer to browse statics, activators and other similar base objects placed by references.
My intention is not to make some people happy, but rather have universal solutions to make everyone happy.
Advanced users are happy with this tab as it is. Until recently I've had only a single request regarding this tab from advanced users in the past 4 years - to add Mark Modified option into the right click menu. If I'm ever going to update that tab again, I'd rather write the script I mentioned or implement the same functionality directly in xEdit. Just stacking more hardcoded columns for partucilar reference forms is not something I prefer to do.
