### ISSUE TITLE
FO4Edit: LENS LFSD is an array of Floats and one Integer

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#258]
## CandleFlare02Bright [LENS:001641B3]

```
00 00 80 3F //  float: 1.0
00 00 80 3F //  float: 1.0
00 00 80 3F //  float: 1.0
00 00 00 40 //  float: 2.0
00 00 00 40 //  float: 2.0
00 00 00 00 //  float: 0.0
9A 99 59 3F //  float: 0.85
CD CC CC 3D //  float: 0.1
03 00 00 00 // uint32: 3
```

Everywhere you see `00 00 80 3F` in a byte array, which is really common, indicates a float or array of numbers. Should I keep submitting issues for these? I think that even if we don't know what to call them, they should still be modifiable, so we can tinker with them in-game. The `hlp` console command lets us hotload plugins, which makes investigating small changes to values like floats really easy.

**Comment by zilav** [comment]
Yes, anything that defines a type out of hex array is worth to update, would make it easier once CK is out (floats, FormIDs). Integers are uncertain since they could be flags and enums too, I'd rather leave them as hex arrays unles you are pretty sure that do they mean.
Only changing names now won't help later at all.

**Comment by zilav** [comment]
Updated.
