### ISSUE TITLE
How do you compile this project?

### ISSUE THREAD

**Issue by LavenderMoon** [TES5Edit/TES5Edit#280]
I've been trying for days to get this project compiled so I can work on weapon mods for FO4. I've tried FreePascal, Lazarus, Delphi 7, RAD Studio XE10, and RAD Studio XE8. The closest I've gotten to getting this project compiled is with XE8, but I couldn't install JVCL because it couldn't find JCL, which not only did I install beforehand, but JVCL's installer also said it installed beforehand. Could ya'll provide a text file in the repo with instructions on what I need to install in order to compile this?

**Comment by fireundubh** [comment]
RAD Studio XE is what zilav and I use. That's the first version (i.e., not XE2, XE3, etc.) You might need to make some changes to build for another version.

### Dependencies

* [madExcept](http://madshi.net/)
* [JEDI VCL](http://jvcl.delphi-jedi.org/)
* [DevExpress VCL](https://www.devexpress.com/products/vcl/) (optional)

### Native Controls

Instead of using DevExpress VCL, you can build with native controls using the DebugLite configuration.

### Virtual Trees Component

1. Open `VirtualTrees\Delphi\VirtualTreesD15PG.groupproj` (15 is the version for XE)
2. Right-click the project and build. You might need to fix the .dpk before this will build.
3. Right-click the project and install.

**Comment by Sharlikran** [comment]
Making instructions on compiling the project would be useless.  No program except Delphi from Embarcadero will compile this because of the overload functions.  Elminster tried to help update Free Pascal so it would compile xEdit but it has never been able to do so.  Because of restrictions imposed by Embarcadero, only a professional version or higher will compile the project.  Trial versions and Starter versions have restrictions built into the command line compiler.

If you would like to purchase their product you can [buy it here](https://store.embarcadero.com/542/catalog/product.s5216/language.en/currency.USD/?id=fbA3xTmjR9) for about $1100.  I would caution you on doing so however.  At the time I got Delphi XE3 you could compile the project with it.  However, if you buy XE10 you may have to change the code before it will compile because of depreciated syntax.  Since Zilav does not have XE10 it's not like he can do it for you.  You would suddenly have to become a Delphi expert.

Also this project is not here for us to teach you how to program in Delphi or what all of our record definitions mean.  So we also won't be writing wiki pages or documents on what the wbByteArray does or wbUnknown, or any of the other functions and procedures.  If you know Delphi already and can understand the syntax of the record definitions you are welcome to compile FO4Dump.  I gave [instructions](http://forums.bethsoft.com/topic/1529894-relz-tes5edit/?p=24540048) to someone on the Bethesda forums on how to compile it.

All you can compile with the trial version is FO4Dump which will dump the contents of a plugin to a text file.  You would change the code in wbDefinitionsFO4.pas and run FO4Dump to make the text file.  Once you found a valid value you could then post your feedback to us.

DevExpress is optional but you can only compile the light version and not the actual version hosted on the Nexus.  You still need the professional version to do that.  Again because of the compiler restrictions.

**Comment by fireundubh** [comment]
> If you would like to purchase their product you can buy it here for about $1100. I would caution you on doing so however. At the time I got Delphi XE3 you could compile the project with it. However, if you buy XE10 you may have to change the code before it will compile because of deprecated syntax. If it does not compile with XE10 we will not be updating the code to do so.

Embarcadero gives you [access to previous versions of XE](http://www.embarcadero.com/products/delphi/previous-versions) with a Delphi 10 Seattle license, and that extends to other versions as well. For example, if you have an XE3 license, you can download XE and XE2, among others. If you have a pre-XE version, you'll have to upgrade though. @LavenderMoon appears to have Delphi 7, XE8, and XE10 though, so that's not an issue. Also, Embarcadero was [recently acquired](http://www.embarcadero.com/press-releases/idera-announces-intent-to-acquire-embarcadero-expands-position-in-database-management-and-developer-tools-markets), so I'd expect some forthcoming changes to pricing.

> Unfortunately we won't be writing wiki pages and documentation on the functions and procedures used in xEdit.

Just knowing Delphi doesn't grant you special knowledge of the project, its organization, and what every piece of code does, and not having that special knowledge doesn't mean you don't know Delphi. Clear code and documentation are essential  to any project of meaningful complexity, and xEdit is no exception. Fortunately, the source is here for everyone to see, so *anyone* could take on that responsibility.
