### ISSUE TITLE
FO4Edit: Standardize VMAD Element Names

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#325]
Some VMAD element names should be standardized to their simplest form. 

Otherwise, working with VMAD element names in scripts is really quite tedious.

Change | To
--- | ---
Script Fragments Info | Fragments Script
Script Fragments Pack | Fragments Script
Script Fragments Package | Fragments Script
Script Fragments Perk | Fragments Script
Script Fragments Quest | Fragments Script
Script Fragments Scene | Fragments Script
Script Fragments Terminal | Fragments Script
Info Fragments Flags | Flags
Package Fragments Flags | Flags
Scene Fragments Flags | Flags
Info Fragments | Fragments
Package Fragments | Fragments
Quest Fragments | Fragments
Scene Fragments | Fragments
Phase Fragments | (Leave parent element name alone since Scenes have both Fragments and Phase Fragments.)
Info Fragment | Fragment
Package Fragment | Fragment
Quest Fragment | Fragment
Scene Fragment | Fragment
Phase Fragment | Fragment
Alias Scripts | Scripts

**Comment by zilav** [comment]
I'll try to simplify that, VMAD is complex by it's nature.

**Comment by fireundubh** [comment]
Looks great! You even eliminated the adapter type branches (e.g., `Info VMAD`, `Terminal VMAD`), moving everything up at least one level.

`QUST VMAD` is still the odd man out with a `Script Data` branch. Intentional?

`*\VMAD\Script Fragments\Script\Properties` vs. `QUST\VMAD\Script Fragments\Script\Script Data\Properties`

**Comment by zilav** [comment]
"Script Data" branch could me missing if scriptName = '' in QUST VMAD (maybe other VMADs too, Fallout4.esm has such cases only in quests) so I had to use wbUnion with struct inside, that's 2 extra branches. Nothing I could do here, xEdit doesn't have optional elements for binary values inside subrecords, only subrecords themselves since this is how Oblivion worked originally.

To be honest Beth's storage methods becoming more weird with each new game. Instead of using series for subrecords for complex data, they started to pile up binary values inside a single subrecord like VMAD in TES5, and now OMOD in FO4.

They probably have a new programmer responsible for this and he doesn't follow common practice of the previous games, because I just don't see the reason why they couldn't split those blobs of data into separate subrecords.
