### ISSUE TITLE
[Question]File selection dialogue and implied dependencies with DLC cleaning

### ISSUE THREAD

**Issue by GrantSP** [TES5Edit/TES5Edit#329]
It's clearly documented there is a difference between "explicit" & "implicit" dependencies and how this can make a difference to edits made in **xEdit** as documented [here](http://www.creationkit.com/TES5Edit_Cleaning_Guide_-_TES5Edit)

To further emphasise this there are examples given of how to select these DLCs in **xEdit** [here](http://www.creationkit.com/Skyrim_Dirty_Plugins_List) that say you must also select Update.esm along with the DLC you want to clean.

Now, my question is this:
### Is this truly the case and if so why? ###

I have cleaned these DLCs many times, and in my experience just selecting the file to clean in the file selector dialogue and allowing **xEdit** to load the necessary extra files is all that is needed. 
In each time, whether I select Update by hand or allow xEdit to do it, the number of *ITMs* & *UDRs* that are removed is identical.

**Comment by zilav** [comment]
Update.esm is a special case in Skyrim since it is hardcoded to be always loaded, so it is an implicit dependency for any Skyrim mod. DLCs don't have common identical records with Update.esm hence it doesn't matter if you select it or not. Actually there is a very little chance that any mod will have records identical to Update.esm and not having it as explicit master at the same time.

**Comment by GrantSP** [comment]
Thank you, as I expected. At least that clears up something I was discussing elsewhere.
