### ISSUE TITLE
FO4Edit: Race State Groups

### ISSUE THREAD

**Issue by kamicane** [TES5Edit/TES5Edit#331]
I'm toying with animations and I noticed the animation State Groups (found in HumanRaceSubGraphData and other races) are weirdly grouped: The keywords (SKAD) for any given group are put in the previous group, and the keywords for the first group are put outside.

This is how it looks:
![skad-1](https://cloud.githubusercontent.com/assets/7131/12559651/9ad771ee-c396-11e5-8376-9655169a86a1.gif)

The injured keywords belong to the first state groups, AnimArchetypePlayer belongs to the second, and AnimArchetypeNervous belongs to the next one.

This is how it should be:
![skad-2](https://cloud.githubusercontent.com/assets/7131/12559661/a87eb794-c396-11e5-9ee0-75d24ce9e5fc.gif)

**Comment by zilav** [comment]
I know, this is to make RACE records copyable otherwise they wouldn't work.

**Comment by VlitS** [comment]
Did you have to do the same thing for the Tint Template groups? I am trying to make a new group (so I can have certain skin tints use a different base texture. Since the tints are an overlay, it is impossible to use the tints to get certain colors unless you change the base texture as well), but when I try to load the game it just gets stuck when I load a save or start a new game. To clarify it doesn't freeze, but the initial load screen (the one with the same background as the start menu) just plays forever. I'm guessing it is trying to load it, and since I didn't set everything up right it just keeps looking for something I didn't add.

**Comment by zilav** [comment]
Nope, they are working as intended. You probably made wrong changes. Not sure why are you trying to modify them since a lot of values there are unknown and we don't know how they interact together.

**Comment by VlitS** [comment]
I'm impatient, and don't feel like waiting for the CK. I did figure out part of what I was doing wrong, and can know add new facial features (face paint, markings, etc...). I might even be able to add a new category of facial features, it depends on if certain values are dynamically combined or if they point to a list somewhere, I'll have to test that out. Sadly, there is something about the way skin tints are done I haven't figured out yet, so it just resets your skin color to default and ignores any changes you make in the character creation menu.

If you're interested, the biggest problem was two-fold: 
1) you can't give color options when the thing you are adding has a normal and specular map as well. Base and normal works fine, and base and specular for some reason causes it to use the texture of the entry above it.
2) Order Very much matters with tint group records. Specifically, part of the TETI value is used to specify the order of facial features within a category, and the TTGE field is used to indicate the end of a group.

Still don't have everything figured out with facial features. Despite setting what seem to be the relevant values (looked at multiple instances of features with color options), it still has an opacity slider instead. 

Also, number two means adding additional choices to any category but markings (the last one) would be a pain in the ass, since you would have to create a new tint group, then right click -> Move up over and over until you get it in the right spot. Maybe once I figure out scripting for xEdit, I could make something that does that for you.

**Comment by zilav** [comment]
Such huge arrays are not suited well to be edited in xEdit, it's vertical data view was made with intention to compare records, not to manipulate them conviniently. It is possible to write a GUI script similar to Weather Editor script but for races, however once CK comes out it'll beat this anyway since official editor provides real time preview.

**Comment by zilav** [comment]
Fixed.
