### ISSUE TITLE
FO4 v1.5: VMAD Error

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#345]
In the Survival Mode Beta (v1.5), there's a problem with VMAD. Not sure how to describe it.

Affected record: `HC_Manager [QUST:0000080E]`.

![Screenshot](http://i.imgur.com/UnqexTm.png)

**Comment by zilav** [comment]
This is not a vanilla record, so unless you can tell what exactly you've done I don't have anything to say.

**Comment by zilav** [comment]
By the way what's the VMAD and object version at the top of VMAD? Disable all "hide" options to see them.

**Comment by fireundubh** [comment]
> Actually I don't have the latest beta if it is a vanilla record, they probably changed something in VMAD format.

The v1.5 patch updates Fallout4.esm, so it is a vanilla record.

> By the way what's the VMAD and object version at the top of VMAD? Disable all "hide" options to see them.

* VMAD Version 6, Object Format 2
* Record Form Version 131

**Comment by Hugues92** [comment]
I forgot to take the ESM with me this morning :) I'll try to check later.

**Comment by zilav** [comment]
So the format versions remained the same. Judging by your screenshot, property type is 0 which means no property, so the "flags" field should be omitted too probably (made into wbUnion paired with wbEmpty) and that 16 value is actually a length prefix field for the next property name "MessageToDisplay".
Since they disabled mods in beta patch, I'll wait for the official patch pesonally.

**Comment by Hugues92** [comment]
Is there any property of type 6 in Fallout4.esm or DLCRobot.esm ?

**Comment by Hugues92** [comment]
Commited.
