### ISSUE TITLE
FO4Edit: Update to handle Star load order method

### ISSUE THREAD

**Issue by Omolong** [TES5Edit/TES5Edit#349]
As the title says, DLCworkshop01.esm is being forced to load at the bottom of the load order. Even if I change Plugins.txt or loadorder.txt, to put it with the other DLC, it will still only load at the bottom. I did notice that FO4Edit has it as DLCWorkshop01.esm as opposed to the filename being DLCworkshop01.esm (note the upper case W in the FO4Edit name), but even changing the name to match the FO4Edit one didn't do anything to fix the issue.

**Comment by Sharlikran** [comment]
Remember there is no versioning for the Alpha.  Always use the latest version available from the Nexus.  I don't have this issue with the latest version FO4Edit 3.1.3 - 8eb0b5b.

**Comment by Omolong** [comment]
I am using the latest version from the Nexus. I even redownloaded it to check, and the issue is still present.

I did a little bit more investigation, and if I remove loadorder.txt, FO4Edit does display DLCworkshop01.esm at the top with the rest of the ESMs, but FO4Edit then completely ignores the order of the plugins in Plugins.txt. It looks like the order of the plugins follows one of the created/modified/accessed dates (I believe it's the modified one), but that's not the most useful order for it to follow unless you're using something that adjusts the date for you.

**Comment by Sharlikran** [comment]
![loadordertest](https://cloud.githubusercontent.com/assets/1912426/14583078/ff8e6690-03cb-11e6-93fe-2f7a769839ef.jpg)

Those were my test files.  I used both loadorder.txt and plugins.txt.

![fo4edit_lo](https://cloud.githubusercontent.com/assets/1912426/14583089/1ca1d104-03cc-11e6-9eab-087b73857238.jpg)

That was the result in FO4Edit.  Even with the DLC ESM files not in plugins.txt I still can't reproduce your error.  Only tools should manage those files.  Doing it manually and making a mistake can be misleading.

Are you using 1.4 or the Public Survival Beta?  If you are using 1.4 then LOOT 0.8.1 is best.  If you are using the Public Survival Beta let me know and I can make some suggestions.

Aside from all that there are other things happening at this time.  So this is not a bug at all.  Bethesda has the live 1.4 patch and there is a Public Survival Beta.  I work closely with LOOT, FO4Edit, and Wrye Flash.  FO4Edit and LOOT are updated to work with the new load order system used by the Public Survival Beta.  Wrye Flash has support for the Public Survival Beta but it still needs tweaking before I can release it on the Nexus.  

All three tools will be ready once the Public Survival Beta is no longer in Beta and is the current official live patch.  However, as you can see it still works with 1.4.  I'm sorry it's not working as well for you.

**Comment by Sharlikran** [comment]
If you want I can also see if your loadorder.txt and plugins.txt are out of sync.  If you can get me a copy of both files I'll take a look at them.

**Comment by Omolong** [comment]
I've got the Survival beta, yeah. The order of the plugins in loadorder.txt and plugins.txt are the same, the only differences are plugins I don't have enabled and the obvious asterisks needed to load plugins in the beta. I've been using NMM to set the order, and I've then used Notepad++ to add the asterisks to the lines for me, so I don't see there being a mistake casued by manual editing that would cause this. I did check, though, and DLCworkshop01.esm is definitely only located at the top with the other ESMs in both files.

There does seem to be an issue with FO4Edit following one of the file dates as opposed to the order of plugins.txt, though (or at least, that's something I haven't seen noted anywhere as being intentional). I created a new version of one of my mods and gave it a new plugin file, which I put it just underneath the older version, which is in the top half of my load order. When I opened up FO4Edit without loadorder.txt present, it picked up that the file was activated, but it was at the bottom of the load order, along with other recent mods I've installed (which should be in other places in the load order too). 
![fo4edit_2016-04-17_01-05-35](https://cloud.githubusercontent.com/assets/368472/14584319/088df2c0-0439-11e6-8137-446a0e9040e7.png)![fo4edit_2016-04-17_01-05-52](https://cloud.githubusercontent.com/assets/368472/14584320/0da6f202-0439-11e6-85d8-f4047b4c03bb.png)
The first one is how it should look (outside of the position of DLCworkshop01.esm), and the second one is how it looks without loadorder.txt present. I've got no idea if this would cause the issue I've been having with DLCworkshop01.esm, but I thought I would bring it up in case it is somehow involved.

I did try running my loadorder through the latest LOOT snapshot to see if that would help (and I moved loadorder.txt out of the folder as I noticed that it wasn't changed by LOOT), but it made no difference to my load order in FO4Edit, outside of where my unactivated plugins were positioned. Everything still seemed to be based on the file date instead of the plugins.txt positions.

**Comment by Sharlikran** [comment]
Question to @Zilav and @Hlp:  Because this has been brought to our attention I want to ask about the current behavior of xEdit in regards to altering loadorder.txt and plugins.txt.  Does any version of xEdit read the Data folder and then add or remove entries from loadorder.txt or plugins.txt as of `` FO4Edit 3.1.3 - 8eb0b5b``?

-------------------------
@Omolong, If you are using the Survival Beta then I recommend using LOOT v0.8.1-308-ge74fce2 (32 bit) from the snapshot folder fallout4-1.5-support.  If you delete loadorder.txt you will notice that LOOT won't make a new one.  The other thing LOOT will do is a silent alteration of plugins.txt.  Any file not in the Data folder but in plugins.txt will be removed.  Any file in the Data folder not in plugins.txt will be appended to the bottom of the list without an asterisk.  LOOT will remove Fallout4.esm from the begining of plugins.txt if present.  This is intended behavior by WrinklyNinja.  

This is also the current behavior for Wrye Flash with the exception that it will add Fallout4.esm if missing since it can't be activated or deactivated in Wrye Flash..

I appreciate all the feedback and testing.  Hlp has been trying to come up with a solution and I'm sure he can work it out.  However, with the major tools in Fallout 4 modding not creating loadorder.txt it won't exist and it's probably best if FO4Edit doesn't look for it.

### Summary of Current Support for the Survival Beta:

- LOOT: does not provide the option to activate or deactivate mods.  It will only sort plugins.txt and add or remove files from the list depending on the files found in the Data folder.  Currently supports Star Load Order.
- Wrye Flash: Provides an option to activate or deactivate, Install and uninstall, and sort mods.  Wrye Flash will not sort loadorder.txt.  Currently supports Star Load Order.
- NMM 61.16: Provides an option to activate or deactivate, Install and uninstall, and sort mods.  Currently doesn't support Star Load Order and will remove all the files with the asterisks from plugins.txt. NMM will also set plugins.txt to Read-Only with no option to disable it that I am aware of.  Preventing LOOT or Wrye Flash from altering plugins.txt.

### Unmanaged loadorder.txt:

Tools that support Star Load order and use WrinklyNinja's DLL (which usually includes the NMM team) will end up causing plugins.txt and loadorder.txt to be out of sync.
![loadordermismatch](https://cloud.githubusercontent.com/assets/1912426/14584650/60a71a6a-0405-11e6-9ab3-eeb4fe3b42f0.png)
Once loadorder.txt is out of sync tools that continue to use it will get confused and will not sort plugins as users expect.

**Comment by zilav** [comment]
Yes, xEdit scans the data folder for plugins and those that are not in loadorder.txt and plugin.txt are appended at the end. Once the official patch is out we'll remove reading of loadorder.txt

**Comment by Sharlikran** [comment]
Thanks Zilav.  I updated my post.  Does only FO3/FNV/TES4 use a time date stamp or do you use a combination of pluginst.txt and loadorder.txt?

**Comment by zilav** [comment]
Only TES5 and FO4 use loadorder.txt right now, older games use timestamps since plugins.txt is unordered there.

**Comment by Sharlikran** [comment]
@Omolong Alright now everything is verified and I updated my posts.  For now while all tools and Bethesda live patches and Survival Betas are going on don't expect tools to behave the way they are intended to.

For Fallout 4 for best results don't use loadorder.txt with LOOT or FO4Edit.  You will need to decide how you are going to approach the use of NMM since it will keep making one.

**Comment by Sharlikran** [comment]
Even after all the tests now I'm seeing odd things.  With both of the recent version I have this which is incorrect.
![currentlo](https://cloud.githubusercontent.com/assets/1912426/14592337/596ea63c-04d2-11e6-8419-1b2a0f021d5e.jpg)
![fallout4lo](https://cloud.githubusercontent.com/assets/1912426/14592339/5b8251d0-04d2-11e6-9a20-02542d390ac8.jpg)
I'll have to wait and see how the new changes work once it's available.

**Comment by Sharlikran** [comment]
Just adding this so it's in the ticket.

 - Fallout4.esm
 - Any DLC listed in plugins.txt in the order found. (1)
 - Add DLC found in Data folder but not listed in plugins.txt in order of publication with an asterisk. (1)
 - Any active or inactive ESM or false flagged ESP(2) in plugins.txt in the order found.
 - Add all ESM or false flagged ESP(2) found in the Data folder not in plugins.txt in an undefined order.
 - All active or inactive non esm flagged plugins in plugins.txt in the order found.
 - Add all non esm flagged plugins found in Data but not in plugins.txt without an asterisk in an undefined order.

1. We can't force a specific order for the DLC because unofficial patches will be between them.
2. Plugin with ESM flag

**Comment by Omolong** [comment]
Yeah, I'm definitely using the build of LOOT mentioned earlier. I made sure to download it to avoid issues with with the Survival beta. From what I understand about the changes to plugins.txt, it does make sense for the tools to ignore loadorder.txt, and hopefully there won't be too many tools trying to use it alongside plugins.txt.

For the time being, I have to use loadorder.txt to get my plugins to load in (mostly) the correct order, seeing as it does appear that FO4Edit's order is based on the timestamp without that file. I did a quick comparison of the Windows sort by date modified order and the FO4Edit one, and they do appear to be pretty much identical, from what I could see. Hopefully the recent commits on here (or ones in the future) will fix this problem, and I'd be willing to help test it once a build with the changes is available.

**Comment by Sharlikran** [comment]
Zilav, I was trying to use Sort Masters on a plugin I made and I can't because of how xEdit is reading plugins.txt.  When you have time if xEdit is working enough for you with the changes in 293cddb8a942363ea161f10cec9e3782fcefb2f9 can you make a new version so I can test Hlp's changes and see if they are sufficient?

**Comment by zilav** [comment]
You want me to push a new build on nexus?

**Comment by Sharlikran** [comment]
Why don't give me a link in e-mail.  I'll test it first then I can comment if it's not doing what it should.

**Comment by Omolong** [comment]
I've tested the latest build that was put up the Nexus in the last day or so, and it looks like it's now properly reading the order in plugins.txt. Thanks for fixing it! I think that this issue can be closed now, but I'll let one of you guys handle that just to be on the safe side.
