### ISSUE TITLE
FO4Edit - Extreme slowdown when viewing/editing interior cell records

### ISSUE THREAD

**Issue by thelapdragon** [TES5Edit/TES5Edit#371]
Pretty much like it says on the tin - if I make a change to a cell record (I'm working in the DLCRobot esm, pumping into a normal override esp), xEdit takes several seconds to register a simple drag/drop of one field to another, or to accept a hand-typed entry.  Interior cells seem to be more seriously impacted than exterior.

**Comment by zilav** [comment]
Say thanks to Bethesda for storing thousands of precombined entries in a single record instead of using separate records. Since xEdit dynamically updates the view all the time which involves sorting those arrays for aligned comparison, it is very slow for cells with a huge number of precombined meshes.

**Comment by thelapdragon** [comment]
I've actually deleted the precombined data for my esp, and if I roll back to an older copy of xEdit, while it does take a while to do things in huge cells like the Lair, it's nowhere near the kind of time that the latest version from Nexus needs.

**Comment by zilav** [comment]
Because I turned on sorting of precombined data in the latest build so xEdit can align it for conflicts resolution, people were compaining that xEdit shows a conflict in cells while they didn't change anything.

You can thank Bethesda again for randomly shuffling precombined data each time you save a plugin.

**Comment by thelapdragon** [comment]
Ah-ha...  stupid Bethesda :-)

Any chance you can add a command-line switch to turn that feature off if desired?

**Comment by zilav** [comment]
Does it matter that much? There is almost no lag in majority of cells that have thousands of precombined refs. The only exception are cells with dozens > 10000 refs, they are very few and you don't have to edit them every day I believe to justify switches.
