### ISSUE TITLE
[suggestion] Themes

### ISSUE THREAD

**Issue by CyborgArmGon** [TES5Edit/TES5Edit#384]
This is simple. I mod with Tes5Edit for hours at a time. The Thin black text on white EVERYWHERE kills my eyes.

Is there a way to implement themes? Because my eyesight would thank you.

**Comment by zilav** [comment]
You can change colors in Options.

**Comment by CyborgArmGon** [comment]
You can change two highlight colors, that's it.

**Comment by zilav** [comment]
You can change conflicting colors background and font. Also xEdit sould be theme aware so if your Windows has dark background it must the same in xEdit too.

**Comment by CyborgArmGon** [comment]
I'll look But i saw no such option.

**Comment by eFrysTon** [comment]
[SSEEdit-05113b8](https://github.com/TES5Edit/TES5Edit/releases/tag/SSEEdit-05113b8) contains 2 relevant changes:
- if the native windows color scheme is configured with light text on a dark background, will adapt the background (conflict all) and text (conflict this) colors (background darker instead of lighter, text lighter instead of darker)
- in the system menu (that's the application icon in the top left corner of the window) there is a "Themes" entry where you can select from a number of different colored themes for the UI in general (both light and dark themes in the list, if a dark theme is selected, the mechanism mentioned above activates).

**Comment by Amnesiac9** [comment]
Maybe it could be made easier for xedit to change the background and text colors? this isn't very user friendly
