### ISSUE TITLE
Prune Orphaned Data Option

### ISSUE THREAD

**Issue by rarcher** [TES5Edit/TES5Edit#398]
In the course of modding, the Data folder tends to accumulate a lot of loose file debris...remnants of uninstalled mods, files corresponding to deleted records...stuff like that. Using a mod manager mitigates this problem to some extent, but doesn't completely solve it.

Since TES5Edit has to process all the plugin files anyway, it would be nice if there was an option to automatically examine the Data paths they point to, and remove any assets that are not referenced by any `esm` or `esp` file.

**Comment by zilav** [comment]
You are using the wrong mod manager. For example Wrye Bash has an option to remove all assets not belonging to the currently installed packages.
This is a problem of managing mods and thus mod managers, not of xEdit.
I never had such problems since I use Wrye Bash for all games starting from Morrowind.
