### ISSUE TITLE
[Bug] UI

### ISSUE THREAD

**Issue by RoyBatty64** [TES5Edit/TES5Edit#404]
Dragging or copying records with null entries cause an error and do not copy the contents to the new record.

To reproduce, load FalloutNV.esm and go to record B0768 and try to copy it into a new plugin, or create a new form, compare the records and try to drag the conditions over.

A sub bug with Camera Path, when adding a condition, setting VATS value function to Weapon Type Is and then editing the field does not create the child copy of the entry.

**Comment by zilav** [comment]
That records checks "Weapon Is" on a NULL form, which xEdit considers an error. So the real question is - are such checks valid and actually work in game (for example to check for unarmed state, idk), or it is a true error in vanilla? I can add NULL to the allowed forms list and it'll copy such records, but Checks for Errors won't catch them anymore.

That missing "child" value is only a display issue because of how definitions are made for this particular value. When you reload plugin it'll be there.

**Comment by RoyBatty64** [comment]
While this is a bug in game and should be fixed, it's a leftover record from Fallout 3 which was valid there, it was changed to null because the weapon form was deleted. However you can insert a new condition and it's null by default so being able to copy or drag it should be possible as well? There are many instances of null records and being able to copy them into an override plugin to fix them should be possible to do. It's not only this form type which has that issue, most of them do. I don't know how you would handle such situations or why error scanning is linked to that particular functionality.

This cropped up when I was fixing the error in an override patch for YUP, but I had to use a work around to get the correct records back in place.

Noted about the "child" entry, it's not really there and is purely visual.

**Comment by zilav** [comment]
Then I'll leave it as is. Prefer to catch errors over copying records with errors.
Newly added values are always zero/null if not set otherwise in definitions.

If you have examples of where NULL is not an error but xEdit treat it as an error, then I'll fix that.

**Comment by matortheeternal** [comment]
Would it be possible to have a record copying function which ignores errors?

**Comment by zilav** [comment]
Disable the check in the source code of TwbFormID class if you really need that for your task.

**Comment by matortheeternal** [comment]
monkey patching a removal of all error checking isn't really a solution.  perhaps a global boolean switch could be made to disable error checking, similar to how in MySQL you can disable foreign key checks before doing certain operations, and then re-enable them later.  then a user could disable error checking, copy the records, then re-enable error checking.

**Comment by zilav** [comment]
This option is not needed in the base xEdit code base, it serves no purpose. xEdit is specifically built around data integrity. For your needs, the local monkey patching is the only option if you really need it.

**Comment by matortheeternal** [comment]
The cost to users of Merge Plugins and users who merge plugins manually of having to "fix" errors prior to copying records is very high.  Because of the lack of the ability to copy records with errors in them I have to require users to clean all errors in plugins prior to merging, even if the errors are not an issue in the game engine.  The fact that you cannot copy elements with errors in them is frankly absurd.

**Comment by JohnsonNicholas** [comment]
Or.. not. Merge Plugins does things that really aren't technically supported by the devs, and I can see no valid reason why you should force merge plugins past errors. Fix the errors first and anyone who properly cares about data integrity should not just blindly skip them.

Also: 'errors not an issue in the game engine' u wot mate?

**Comment by matortheeternal** [comment]
> Merge Plugins does things that really aren't technically supported by the devs

By their choice and to the inconvenience of thousands of users...

> I can see no valid reason why you should force merge plugins past errors. 

Here's several:

1. The errors are actually valid.  Example: Elysium Estate has a plant which, when harvested, yields a key to the house.  xEdit thinks this is an Unexpected Reference, but it is technically valid.  Attempting to copy the record in xEdit will raise an exception, whether done from a script or the GUI.  Fixing the error will break the plugin's functionality.
2. The errors cannot be easily fixed, and the plugin functions fine with them.  Example: many plugins with unexpected/out of order subrecord errors are handled correctly by the game engine.
3. The process of merging shouldn't give a shit about whether or not there are errors in the plugins, it should just combine them, no questions asked.  Clean plugins are important, but there's no good reason to enforce that upon users prior to merging, especially when a number of "errors" reported by xEdit are benign.  Unresolved references are almost always treated as NULL references by the game engine.  The allowed FormID lists for unexpected references are overly-limiting and don't get updated in a timely fashion.  Unexpected/out of order subrecords can be difficult to fix, and many plugins with them do not cause issues in the game engine.  Deleted references only cause crashes in certain very specific circumstances.

Don't get me wrong, errors *SHOULD* be fixed, but xEdit should be able to copy a record regardless of whether or not there are errors in it.  At the most it should display a warning message, allowing the user to ignore the force the application to copy the records.  The application should not arbitrarily restrict a user from making certain actions unless the actions absolutely and always cause serious issues, that's what you call **bad UX**.

    The record you are copying has the following errors:
       - Blah
       - Blah
    Copy anyways?
    [ YES ] [ NO ] [ YES TO ALL ]

**Comment by zilav** [comment]
A lot of subjective opinions. If xEdit reports false positive errors, then record definitions should be updated which I always do when people bother to report such issues.

Like I said just disable those checks in your copy, it'll require changes in like 3-5 lines of code only. It probably took more time for you to write all of this :)

**Comment by matortheeternal** [comment]
> Like I said just disable those checks in your copy, it'll require changes in like 3-5 lines of code only. It probably took more time for you to write all of this :)

Yes, but then there's the added cost of, whenever I want to update the xEdit library, I have to re-apply those changes to my code, along with any other monkey-patches I've made.  It's just creating more work for me, which sucks.  I'm the biggest user of xEdit as a library, so I would think my suggestions would have more weight, but that never seems to be the case.

Honestly, I think I just need to maintain my own branch of the xEdit codebase (which is also more work), because I can't get any of the changes I want/need on the main repo.  xEdit is far too conservative and inflexible to make any meaningful changes, and it absolutely sucks for the community as a whole.

**Comment by zilav** [comment]
Pity to hear that I'm the reason of community suffering after all those years. Looks like I need to step back.

**Comment by matortheeternal** [comment]
> Pity to hear that I'm the reason of community suffering after all those years. Looks like I need to step back.

Never said that.  I don't question the absolutely ***massive*** contributions you've made to the community, and your amazing and generous work maintaining xEdit.  I just fundamentally disagree with your design decisions for xEdit.  The central tenet behind your decisions is "maintain the status quo", and that's just very different from how how I operate.

I do feel that xEdit as a whole has a lot of fairly serious issues.  The code is poorly organized, the user experience is abysmal, and the functionality hasn't really improved since it was first created.  This has been one of my primary motivations behind creating xEditLib, and later zEdit.

**Comment by Hugues92** [comment]
You really cannot help yourself. On any subject you HAVE to impose your point and view and never accept that somebody would not share it.

**Comment by matortheeternal** [comment]
> You really cannot help yourself. On any subject you HAVE to impose your point and view and never accept that somebody would not share it.

I didn't even make this issue, I just thought it was a really good idea.  In considering the value a fix for this issue could offer I realized that a lot of common challenges I have seen users facing using xEdit and derivative applications/scripts could be mitigated with a relatively simple improvement.

This isn't about me, it's never been about me.  This isn't really a matter of a contradictory "point of view", there is overwhelming evidence in support of the idea that xEdit's inability to copy records with errors makes a large number of use cases highly impractical.

**Comment by Hugues92** [comment]
Bullshit. It is about you and your damm politic that your permanently try to impose on everybody else.

**Comment by matortheeternal** [comment]
Yeah, that's exactly it.  I'm just an evil politician trying to impose my will on other people for my own benefit.  /s

**Comment by matortheeternal** [comment]
I apologize for my somewhat fierce position on this subject.  I do only want to help - it's not my goal to usurp or undermine what you guys have done here.  I absolutely respect that you manage this repository, and you have made massive contributions through it.  I do hope that I can continue to offer valuable contributions in the future, and I understand that you have made a your decision on this issue.

**Comment by RoyBatty64** [comment]
This post is neutral.

zilav's usual solution to these things for me is to add the IKnowWhatImDoing check to override the functionality for expert mode.

I understand your position on making things "safe" for standard users, however I much appreciate it when expert mode allows me to make these decisions. When the "error" form is in the base game esm(s) it cannot be fixed first because editing those is disabled. That was the reason I originally opened this issue.
