### ISSUE TITLE
[Feature] Drag&Drop FormIDs from Tree to Editors

### ISSUE THREAD

**Issue by jmonachesi** [TES5Edit/TES5Edit#405]
If it's simple to enable dragging nodes from the tree, it would be useful to be able to drag and drop them into references editors to speed up filling leveling lists for example. Just like it's possible between the grids.

Currently I use a  script to copy the whole FormID and then I paste it into the editor, but to enable the cell editor xEdit has to load all the references to fill up a combo (I suspect) so it takes some time to allow editing each cell.

**Comment by zilav** [comment]
This is not logical because trying to drag from the left tree changes the focus and selected record which will in turn update the right pane and dragged value will end up in intself.

Besides there are several ways of copying values between records already present in xEdit which cover all possible situations: Ctrl+C and Ctrl+V, drag&drop between overrides, drag&drop between different records in compare selected mode, "copy to selected" menu option, and custom scripts of course.

Looks like you just don't have enough experience with xEdit if asking for this.

**Comment by jmonachesi** [comment]
It's true, currently the tree control nodes get activated in the mouse down event. Usually controls that have drag&drop enabled activate when the mouseup event is received (I don't know much about delphi but I suspect it's the same for all windows controls). Anyway as you said there are plenty alternatives, but I'd love to know a quick way to reference for instance an ARMO record into a LVLO entry without having to type the name, specially when the leveled list is long.

**Comment by zilav** [comment]
Go to the ARMO record, press Ctrl+C on "Record Header\FormID" field, then you can paste it with Ctrl+V anywhere.
