### ISSUE TITLE
CNAM F2 issue

### ISSUE THREAD

**Issue by CyborgArmGon** [TES5Edit/TES5Edit#406]
When hitting F2 in a CNAM - Created object, specifically in Construable object, TES5Edit Freezes and must be force-closed.

**Comment by zilav** [comment]
It takes some time to build the list of all acceptable records if a lot of plugins loaded.

**Comment by RoyBatty64** [comment]
Could you add some caching of the records after it builds them first time? It would stop the random out of memory crashing too when the garbage collection can't keep up.

**Comment by zilav** [comment]
I've never experienced random out of memory crashes when opening those dropdown lists. Records can be cached in theory, but the cache will have to depend on checksums of plugins or something like that. It also will be invalidated by overriding plugins because they can change the names of records. So it is not that simple and obvious solution as it seems for a not very important problem since it affects only limited number of fields in a limted number of records. My intentions right now is to add better nif support to xEdit, maybe after that I'll take a look.

**Comment by RoyBatty64** [comment]
Caching for only that session, so it's not rebuilding the list every single time which can take quite some to do with many plugins loaded.

Rarely the garbage collection cannot keep up if you are adding a bunch of things to a form list for ex, and it will crash with an out of memory error. I never reported it before because it's another "sometimes" thing and I don't want to waste time trying to record it.

**Comment by zilav** [comment]
This will require a more broad approach like implementing the chached "map" of plugin which will hold FormIDs, Names and references of all records, verified by checksum. Not something I'm going to do any time soon.
