### ISSUE TITLE
FO4Edit counts .esl files in the 254 file limit

### ISSUE THREAD

**Issue by mlandstreet** [TES5Edit/TES5Edit#449]
I apologize if this has been covered. I could not find it.

I finally decided to load creation club content into my game this morning but of course wanted to take a look at it in FO4Edit first. 

I have 36 .esl files and 224 .esm/.esp files. 4 of the .esl files are from nexus mods. Attempting to load into FO4Edit gives me:
![image](https://user-images.githubusercontent.com/18373744/34908209-dfa4d20c-f851-11e7-8a91-2f23db81d383.png)

The message tab shows:
[00:00] Background Loader: starting...
[00:00] Background Loader: Too many plugins selected. Adding 260 files would exceed the maximum index of 254
[04:40] Background Loader: finished

Does xEdit still have the 254 file limit? 

Let me know if I need to gather further info.

Thanks,
Mason

**Comment by zilav** [comment]
It has a limit for plugin files in total regardless of their type.

**Comment by mlandstreet** [comment]
Is there any plan to make xEdit expand to the new plugin limits that are supported by FO4 and SSE?

**Comment by zilav** [comment]
Not yet.

**Comment by jchamlin** [comment]
I talked with zilav in chat earlier this morning. Basically, xEdit will load .ccc files (ESL files from CC) at the top, and then mod .esl files as if they are .esp files. So, just make sure your plugins.txt has them in the right order:
master .esm files the order you choose
master .esl files in alphabetical order
non-master .esl files in alphabetical order
.esp files in the order you choose

And then load that into xEdit and it will properly display conflicts the way they would appear in-game and allow you to resolve them by rearranging load order and restarting xEdit, or building patches.

Even though Fallout 4 now allows more than 255 plugins by using .esl files, unfortunately, xEdit internally uses a byte as the internal load order, so it still has a limit of 255 plugins total. That is not likely to change anytime soon, since there are higher priority items on the xEdit backlog. You can use xEdit as you always have, with .esl files following the directions here, but only as long as you have less than 255 plugins. If you need to do conflict resolution with your plugins and you have more than 255 of them, then when xEdit launches and allows you to select plugins to load, you will have to select less than 255 in order to do your checks and editing in xEdit.

**Comment by mycumycu** [comment]
> maybe zilav could just add another context menu item to the select plugins popup window to exclude plugins that do not have any overrides and are not referenced by other plugins

Would it be possible to add such functionality? 
Having a really hard job to resolve conflicts with 394 (252 ESP/142 ESL) active plugins...
