### ISSUE TITLE
SSEEdit throws registry key error when opening .tes5pas

### ISSUE THREAD

**Issue by dragonjet** [TES5Edit/TES5Edit#462]
My `.tes5pas` is associated with SSEEdit as its handler.
When I try to execute `.tes5pas`, it shows the following error:

![sseedit_2018-04-18_08-54-51](https://user-images.githubusercontent.com/557312/38906051-e87b5e16-42e6-11e8-92d8-80c87b50d131.png)

It seems on init, the game name is not initialized as special edition, and still looking for Oldrim

This happens both when running raw, and running via MO2

**Comment by dragonjet** [comment]
It came to my mind but I didn't think it would work so I didn't. But someone in discord told me to try it, so I renamed it to `.ssepas` and it worked!

**Comment by Sharlikran** [comment]
The error message told you what the issue was and the solution. There is also a readme that comes with xEdit. For Skyrim you rename the EXE to TES4Edit and for Skyrim SE you name it SSEEdit. Then for both games you run the official launcher which looks like this.

![image](https://user-images.githubusercontent.com/1912426/43682954-759961f8-9837-11e8-91dd-487752a3c7da.png)

**Comment by dragonjet** [comment]
Thanks, though when it happened back then, I can run both SSE and SSEEdit just fine. I was confronted with the error message when running my own mod which I wrongly named as `.tes5pas`, which expects oldrim, which wasn't installed on my computer. Renaming it to file extension `.ssepas` work just fine so far, thanks 👍
