### ISSUE TITLE
Large monitor and multi monitor support. [Feature Request]

### ISSUE THREAD

**Issue by RoyBatty64** [TES5Edit/TES5Edit#471]
Currently when resizing the window more than 1920x1080 on a 2K or 4K monitor, upon closing the metrics are reset to default.

This also happens if closing xEdit on another monitor regardless of window size.

**Comment by eFrysTon** [comment]
This should be fixed in [SSEEdit-05113b8](https://github.com/TES5Edit/TES5Edit/releases/tag/SSEEdit-05113b8)

Last saved position getting lost was a bug in the code that verifies that the last saved position falls into the current desktop (to prevent windows from being restored outside the visible desktop).

xEdit should now also be "High DPI"-aware for 4K monitors (can't test that very well, let me know if you still see issues).

**Comment by zilav** [comment]
I was checking that on purpose actually, there were issues reported when users closed xEdit on their second desktop, disconnected it, and xEdit was starting "invisible" outside of currently available desktop area. Though I didn't have second monitor to test how it worked (even if at all), was a blind change.

**Comment by eFrysTon** [comment]
There were two issues with the check. 
a) it checked against WorkAreaRect (main monitor minus taskbar) instead of DesktopRect
b) It checked saved left against rect.top and saved top against rect.left

**Comment by zilav** [comment]
Oh well, happens :)

**Comment by eFrysTon** [comment]
Yeah.. I only noticed it after tracing through it with the debugger a few times, it wasn't that obvious from the source.
