### ISSUE TITLE
AfterSet event on container is not called when container is removed

### ISSUE THREAD

**Issue by zilav** [TES5Edit/TES5Edit#495]
Assigned AfterSet event is not called on container when container itself is removed potentially leaving counter fields.

In ARMO record remove afterset event `], False, nil, cpNormal, False, wbARMOAfterLoad, wbKeywordsAfterSet);` on the record itself so the parent container (ARMO record) has no event and the one on `KWDA - Keywords` is never called when KWDA itself is removed.

Ideally if container is being removed, and it has assigned AfterSet event, and it contains any elements, then remove them first, call AfterSet event to handle counter field, then remove the container.

**Comment by eFrysTon** [comment]
After reviewing the source, the current behavior is what should be expected, because the AfterSet event gets the Element as a parameter. If I would call it after the element has been removed, I would need to pass nil as parameter. In which case there is nothing from which to derive the container of the element that has been removed.

Instead of having KSIZ and KWDA side by side and adding/removing the KSIZ when the KWDA is being changed, the correcter approach would probably have been to use something like:

  wbKeywords := wbRStruct('Keywords', [
    wbKSIZ,
    wbReqKWDAs
  ], []);

(which is already present in source, but never used)

In which case, when you add it, you get the counter and the first entry. And when removing, you can only remove the block as a whole, which also removes the counter, as the last entry can't be deleted in isolation because of the Req.

**Comment by eFrysTon** [comment]
For cases where the counter field is always required, the RecordStruct should be marked as required, but the contained array not. That makes it so that the counter field must always be present.

For cases where the counter field is only present when there is at least one entry, the RecordStruct is not marked as required (so that it can be removed) but the array inside is marked as required (so that you can't remove the last item, only the whole containing record struct, which will remove the count as well.

But it's probably to late to make these changes as I would guess there are scripts around by now that depends on the current structure?

If I would call AfterSet on removing the container, but before doing so, the container wouldn't be empty. Because the code doesn't bother to remove all the entries first, it just removes itself as a whole from whatever contains it.

**Comment by zilav** [comment]
Yes too late to update definitions.
I proposed to add aRemoved boolean parameter to AfterSet event in the case when container is about to be removed but not empty.

**Comment by eFrysTon** [comment]
The AfterSet call that you are currently getting is probably the one from here:
```pascal
procedure TwbContainer.NotifyChangedInternal(aContainer: Pointer);
begin
  if [csInitializing, csReseting] * cntStates <> [] then
    Exit;
  if csAsCreatedEmpty in cntStates then
    Exclude(cntStates, csAsCreatedEmpty);

  inherited;

  if esModified in eStates then
    DoAfterSet(varEmpty, varEmpty);
end;
```
this happens very late AND is controlled by BeginUpdate/EndUpdate. 

Adding that aRemoved (should be aRemoving in this case) and triggering the event before doing the actual removal would not be able to observe eUpdateCount. I don't know what the general effect would be of that.

**Comment by zilav** [comment]
Thanks for looking. This is quite rare to have a container with AfterSet event and parent container without it to watch for removal. I couldn't find such instance, so not that important.

**Comment by eFrysTon** [comment]
I guess we should just keep this general problem in mind whenever the next Beth game comes out that we want to support and consider what we have for existing games as "no pretty, but works"...

**Comment by zilav** [comment]
Fallout 76? :)

**Comment by Hugues92** [comment]
I bought it just to see what's available locally and how the engine binary will change for an online only game.
