### ISSUE TITLE
[Info] Text fields not converted

### ISSUE THREAD

**Issue by dhk-room101** [TES5Edit/TES5Edit#501]
**What is the version of xEdit you are using?**
3.2.1

**Describe the info**
Text fields, such as FULL or DESC, don't convert on custom ESP. Instead only the ASCII character of the bytes show up.

**To Reproduce**
N/A, I use my own C sharp code for bulk copy of selected records

**Expected behavior**
It should convert, as the byte stream is identical using my way or your way

**Screenshots**
see for more info https://1drv.ms/f/s!AtUshxK9rYxAjUmEkiicp9viYoPC

**Additional context**
The link above contains the test ESP file

**Comment by eFrysTon** [comment]
I'm not sure what gave you the impression that this could in any possible way be an error in xEdit instead of your code simply producing broken files, but yeah, that file is broken. You should recheck your code.

**Comment by Sharlikran** [comment]
What that is actually is a pointer to the strings files. Say for example 00 40 FE 3E was the pointer to the string, then xEdit will look within the strings file for the string and display it. For example you should see maybe for a quest, "And the green sword arose from the ground" instead of `Q^`.

The fact that it's not happening isn't a bug. Your mod needs all three strings files located in the strings folder.

[tesvTranslator](https://www.nexusmods.com/skyrim/mods/29148) may have more features for doing that so I would give it a try. I am not sure what kind of Skyrim SE support it has so you will have to ask the author.

**Comment by eFrysTon** [comment]
The file in question does not have the Localized flag.
So, no, there shouldn't be any String IDs in the string fields, only proper ansi (maybe utf8, not sure) text.

**Comment by Sharlikran** [comment]
I can still account for the error and explain it in more detail to help him though. I'm looking something up right now. This is what we encountered when we first started working with ESP files when you first gave me the code.

**Comment by Sharlikran** [comment]
![image](https://user-images.githubusercontent.com/1912426/43741795-6b3b045c-9984-11e8-9182-9b2d5a4c1084.png)

With the xTranslator I was able to point to the correct folders at least.

![image](https://user-images.githubusercontent.com/1912426/43741831-94d7e4a6-9984-11e8-8913-dfaaa6af9f8b.png)

Now after I loaded it you will notice it is telling you the same thing as xEdit is doing. There are no strings files to reference. You have to make them.

![image](https://user-images.githubusercontent.com/1912426/43741911-dcd3e3b8-9984-11e8-94a6-cfd5e1ba42c3.png)

Now see I was able to add in the right column a string of just Bear Claws. I didn't do it correctly obviously. I do not know how to use that program at all. I am not going to make the three strings files and provide them because I don't really have the time.

All I am doing is just saying that your test.esp was not properly made to work as a file with Skyrim SE strings files. It is missing the localization flag and you need to make the strings files. If done correctly you should have a working mod that could be in English and any other language you and your team choose.

**Comment by Sharlikran** [comment]
Indecently xEdit also has a strings editor but I don't know which you would prefer to use. I would have provided a quick screen shot of the Editor but because your `test.esp` didn't have the three strings files I need I can't really get to that portion of xEdit to show you anything.

**Comment by Sharlikran** [comment]
I was going to show you how to do this but in testing it out I got stuck.  Normally I would not do this but I know this is not in the Training Manual which is a PDF linked on each Nexus description page.

So I my instructions won't be complete because I have to ask some questions first. All I can say is it's clear now that you didn't use xEdit or the CK to copy the records because they embed the sting into the plugin as I show below. 

I helped find people to develop TESVSnip, and they gave up because it was so full of bugs. If you used that then know nobody, not even Figment, has ever finished resolving the bugs. Do not use TESVSnip, period. It will cause this issue because it can't handle many many things that it needs to handle in order to make a proper plugin.

![image](https://user-images.githubusercontent.com/1912426/43748861-8c027248-99a6-11e8-8dc7-45b4ef456152.png)

So first I copied a record. However, it is still using the strings file for Dragonborn. There is no mytest strings files and none will be automatically created.

![image](https://user-images.githubusercontent.com/1912426/43748910-c5dc55d8-99a6-11e8-84dd-5dfd39478301.png)

In the above screen shot the plugin has `Boar Meat` for the `FULL` record.

![image](https://user-images.githubusercontent.com/1912426/43749057-6308edd0-99a7-11e8-86f1-08461ad711ab.png)

I don't have a good HEX editor so I'm just going to compare your file with my test file. The highlighted area shows that the string "Boar Meat" is part of the plugin. You will notice it is NOT a String ID.

**Comment by Sharlikran** [comment]
Now because I really wanted to test xEdit I repaired your test file for you and then made the strings files.

![image](https://user-images.githubusercontent.com/1912426/43750743-a52e2534-99ae-11e8-8722-fb71f6af93f4.png)

There is proof of concept.

And the files are attached.

[test translate.zip](https://github.com/TES5Edit/TES5Edit/files/2264729/test.translate.zip)

**Comment by Sharlikran** [comment]
@Hugues92 I figured out how to make the strings file, which I had never done before. However, what was ``-translate`` supposed to do. It doesn't make the strings files automatically.

It doesn't do what I expected. I would think it just builds the strings files and sets the localization flag. I tried it though. I added ``SSEEdit.exe -translate`` and that brings up a plugin selection screen, and then another screen that lets you filter certain records. After that nothing happens. No strings files are made nothing.

**Comment by eFrysTon** [comment]
Translate is like -edit or -view a tool mode (you can rename the exe) which goes back to the early days of TES4Edit. It restricts you to basically editing only the string fields that might require translation. And was meant for translaters so that they don't accidentially make any other changes.

**Comment by dhk-room101** [comment]
@Sharlikran Thank you very much for all the info and help!

**Comment by dhk-room101** [comment]
@Sharlikran I updated my code to add the localized flag in the file header. I also added the plug-in string files, and now everything works as expected. Thank you very much again for taking the time to explain, you've been very helpful!
