### ISSUE TITLE
[Feature Request] Deserialize back to ESP from TXT.

### ISSUE THREAD

**Issue by gir489** [TES5Edit/TES5Edit#530]
FO4Dumper works great, but it  seems to be only way one. Is there a way to get it to parse changes back to an ESP?

**Comment by Sharlikran** [comment]
While I am not opposed to the Idea I'm not a fan. I see no reasonable reason to do this and if implemented I would not troubleshoot the issues caused by editing the records incorrectly. Scripts can handle about any kind of batch process you need. Recently there have been imporvements that allow a script making around 1000 alterations to run in a matter of seconds instead of hours.

When I mentioned this to Elminster his answer was, "I'm happy to accept a pull request with a working implementation..." and I agree. If you or anyone would like to contribute a working model for this request, feel free to do so but it needs to have full support upon completion for all 6 games and all record types.
