### ISSUE TITLE
Help! Fatal: Error loading plugin list: <EOSError: System Error.  Code: 1006. The volume for a file has been externally altered so that the opened file is no longer valid>

### ISSUE THREAD

**Issue by aplanetsabc** [TES5Edit/TES5Edit#538]
[SSEEdit_log.txt](https://github.com/TES5Edit/TES5Edit/files/2338737/SSEEdit_log.txt)

**Comment by aplanetsabc** [comment]
This also only occurs when launching through MO2

**Comment by zilav** [comment]
Then this is a MO2 problem only, open issue at MO's github. xEdit can't control what happens in MO's virtual file system, but it clearly can't open plugins.txt for some reason.

**Comment by aplanetsabc** [comment]
It doesn’t occur with anything else, reinstallling mo doesn’t help, and it clearly is an issue with just the version of ssedit, because all other applications can read it fine :/

**Comment by zilav** [comment]
If this happens under MO and works fine without it, then the issue is in MO.
Software which provides virtualization for other applications should do this seamlessly, not the other way around requiring special support from 3rd applications. Such "virtualization" doesn't make sense.

**Comment by Sharlikran** [comment]
Once Elminater has fixed a completely different issue then what you are reporting, you have a new version to test with. I would guess the new version will become 3.2.56. I'm just guessing.

After that happens then you can test with xEdit to see what it does when you save files.

However, the issue related to plugins.txt isnt something that we can address because we dont change plugins.txt.

What is happening which is why you should not post in multiple places, is that xEdit is scheduling a save for files when they are marked as a file that can't be saved.

For example when you flag a mod with esl flag and the file can't have the flag, xEdit saves the file anyway but it becomes 0kb. That should not happen. So wait for new version.

Then with the new version what should happen is you will see the error, you won't be able to save the file, and then you will just have to close without saving.
