### ISSUE TITLE
Record Flags missing? FormID also appearing as NULL 

### ISSUE THREAD

**Issue by liam122** [TES5Edit/TES5Edit#562]
**What is the version of xEdit you are using?**
xEdit 3.2.2

**Describe the bug**
After selecting a plugin such as a plugin that i know is a ESL and navigating to the file header of that ESL, it says FormID NULL - Reference, As well as under Record flags there is no flag for ESL and right clicking on that row to edit it shows only 3 flags, ESM, LocalIsed and Ignored. No box for ESL at all.

**To Reproduce**
1. Go to 'File Header'
2. Right Click on 'Record Flags'
3. Scroll down to 'Edit'

**Expected behavior**
The expected behavior would have been that i would have been able to have seen that it was a ESL and then accordingly untick the ESL flag making it  be able to be merged using "Merge Plugins Standalone"

**Screenshots**
https://i.imgur.com/iihxoJR.png: ESL Flag not present
https://i.imgur.com/i9egYst.png: No record flags at all, although i know its a ESL and FormID is Null?

**Additional context**
Following the guide known as "Lexys  LOTD SE" it asks to turn these ESLs into ESPs for use in Merge Plugins Standalone otherwise it won't accept them, Although trying multiple reinstalls of xEdit hasn't seemed to have made a difference and as the guide described there should be a ESL Checkbox to uncheck although that still doesn't appear.

**Comment by jbostrus** [comment]
Stop using such an outdated version if you want to support ESL. That one doesn't. The version here on GitHub is so much newer with an S-ton of fixes since then. Hit the "<> Code" Tab and then the "Releases" sub tab.

Here's a direct too.
[https://github.com/TES5Edit/TES5Edit/releases](https://github.com/TES5Edit/TES5Edit/releases)

**Comment by Sharlikran** [comment]
3.2.2 and 3.2.1 are not really supported at this time. For example we won't be making a 3.2.2a with any kind of fixes. The next release will be quite extensive and possibly be given the version number 4.0.

There isn't a GitHub glossary but for common terminology flags are capitalized and file extensions are lowercase. So ESL flag and .esl file.

If the current developmental build from the releases section does the same thing then make sure you communicate with the author of the guide so that they can make some kind of update.

It might be a better workflow to remove all the flags from the .esl file first. Then exit xEdit and rename the file from .esl to .esp.

It is not a current focus for xEdit to make it such that other guides and tools work in a way that the user prefers. I suggest the authors of guides obtain the latest version and update their guide. If other tools do not function as needed then communicate with the author of the tool.

**Comment by Sharlikran** [comment]
@liam122 please test with 3.2.72d and let me know if there are any differences.

**Comment by eFrysTon** [comment]
First, that screenshot shows version 3.2, not even 3.2.1 or 3.2.2 (as your report is claiming), which was released on 27 Dec 2016 and predates the release of any ESL capable game by Bethesda. Sorry that our time machine and crystal ball were broken at that time and we couldn't predict that there will be a flag called ESL in the future.

Second, NULL for FormID is totally normal for the **File Header** record.
