### ISSUE TITLE
Adding a master to a mod turns all its hex FormIDs into injections into that master

### ISSUE THREAD

**Issue by Darklocq** [TES5Edit/TES5Edit#569]
**What is the version of xEdit you are using?**
TES5Edit 3.2.1

**Describe the bug**
I manually adding a master changes the ObjectIDs in an unexpected way. What it appears to do is convert them into injections into the newly added dependency. E.g. what was 059FB39C may become 029FB39C, if the mod you're working on is 05.

**To Reproduce**
Download hdtHighHeel.esm [HDT High Heels physics](https://www.nexusmods.com/skyrim/mods/36213)

1. Open a mod and add a master.
2. Add hdtHighHeel.esm

Example mods: 

[Rebekah.esp](https://www.nexusmods.com/skyrim/mods/74654/?tab=files) (a follower mod)
Emfy Cleric Robes.esp (an outfit mod)

**Expected behavior**
Add the master, with no changes to the mod's own formIDs.

The only workaround I'm aware of is to manually tell TES5Edit to load the dependency and load the mod you want to flag as dependent (add a master to), then copy a record from the former into the latter (a record that has at least one ID reference in it from the mod you want to be a dependency), then go into that mod and delete what you just added.  This gets TES5Edit to add the master to the later mod's header without screwing up the IDs, and it keeps the master even if you remove what TES5Edit thinks made it a master in the first place. 

That works, but it's a ridiculous kludge.

**Comment by Sharlikran** [comment]
![image](https://user-images.githubusercontent.com/1912426/47599772-f8935a00-d969-11e8-8d6a-beb625e72e13.png)

I didn't have any issue updating the plugin you gave as an example.

**Comment by Darklocq** [comment]
PPS: I have never played Fallout anything, and this report has nothing to do with FO*Edit, which I don't have, so I would not have read "the Fallout 3 and Fallout NV training manual".

**Comment by Darklocq** [comment]
Update: Got 3.2.84 going and tested.

* The issue I reported IS resolved; it's no longer possible to try to add a master by editing the File Header records directly.
* However, we've lost the ability to change the name of a master with right-click and Edit, or to delete one, which may be problematic. E.g. if I merge ModA and ModB into MergedModC, and ModD has a dependency on ModB, I can't see a way to update it to depend instead on MergedModC.  I'm a mod nut and do a lot of merging to make more room, so I have to wonder how to effectuate this.
* I'll go over the updated docs (and I see now that the main ReadMe says the FO3- and FNV-related documentation is also for xEdit in general, so I'll go over that all).  I've mostly depended on tes5edit.github.io (though not perused it in several months, so if it's been updated I would not have noticed it yet, and of course did not totally memorize it all the first time).
* The loading process is much, much slower the first time - when I loaded Serana.esp with Dawnguard as a dependency it took over 2 minutes for the background loader to finish, though much less time on a later load). I think this is what you were hinting at in the "After the first execution the references are cached" material above.  If this improves it in some way, I have no complaint.  Slow once and fast thereafter is better than middle-speed all the time.

Oh, I just noticed your reference to TESVSnip, which made me laugh.  Using that would be kind of like brushing my teeth with a razor, ha ha.

Anyway, thanks again for the pointer to the rather bleeding edge version. I hope it's as stable as it seems so far, and I mostly like the interface changes (other than the mod name search function at startup making everything disappear except the matches; I liked the old highlight-it-in-the-mod-list behavior better; maybe there's a setting to get that back that I'll figure out later).

**Comment by Sharlikran** [comment]
> PPS: I have never played Fallout anything, and this report has nothing to do with FO*Edit, which I don't have, so I would not have read "the Fallout 3 and Fallout NV training manual".

That was my point. Those are for all versions, Skyrim, Oblivion, Fallout, because the Training guide just goes over operations not game specific info. However, the online docs make it look more universal I believe.

**Comment by Sharlikran** [comment]
In regards to what I meant about personal comments. The new version communicates with the internet to check for a new version. Suppose someone made a report and didn't know and was simply asking why xedit is trying to access the internet. That's different than old versions so that's a fair question. What I'm looking for is a few sentances asking why it's happening to which I would respond a version check. What I'm disinterested in is the users view of internet security, the great lengths to which the user has to go to prevent programs from accessing the internet, nor any of their discontent toward that feature. 

Again sorry if that seems harsh but it provides no benefit later on and is not

**Comment by Sharlikran** [comment]
Even our comments make reading this unrewarding for others trying to see if there is a simple solution or workaround.

So the solution to add a master is to use the add masters feature. To remove masters you would use clean masters. As mentioned in the docs using remove masters will not work when records are in use because of how that would break the plugin.

Adding or removing MAST records at will is what lead to the change. There was never any automated function to update or renumber ObjectIDs when adding or removing masters as the ability to edit the header directly wasn't meant for that purpose. The automation was built into add master and clean masters.

If you would like, click the discord button, and after reading the channel rules, feel free to comment further there please.

I hope you enjoy the new version.

**Comment by Darklocq** [comment]
It's working beautifully so far!
