### ISSUE TITLE
Assertion failure (P:\TES5Edit\wbImplementation.pas

### ISSUE THREAD

**Issue by thomasandersen** [TES5Edit/TES5Edit#651]
**What is the version of xEdit you are using?**

FO4Edit 4.0.1

**Describe the bug**

Saving crashes after renumbering record IDs in one mod/file. 

Error message:

"Error saving filename.esp.save.2019_02_21_20_55_02: Assertion failure (P:\TES5Edit\wbImplementation.pas, line 14534)"

**To reproduce**
1. Try use a file with 70000+ records.
2. Right click on mod name and choose renumber FormIDs
3. Try starts from: 100000 (I've tried various start id's, but same error occurs).
4. When renumbering is done, save the changes.

**Expected behavior**

Changes to be saved without errors.

I can provide my file if it is necessary.

**Comment by ElminsterAU** [comment]
Please try 4.0.1m

**Comment by thomasandersen** [comment]
> Please try 4.0.1m

Same issue. 

As suggested in the Discord server / support I manged to get around this with using Compact Form IDs in CreationKit

Thanks!

**Comment by ElminsterAU** [comment]
May be resolved in 4.0.2, can you retest please?

**Comment by royrporter** [comment]
FO4edit consistent error only on DLCCoast.esm. Reinstalled DLCCoast with no effect. 
Running FO4edit 4.0.2. 
Restarted everything a few times....

Background Loader: Fatal: <EAssertion failed: Assertion failure (P;\TES5Edit\wbImplementation.pas, line 10181)>. 

LOOT shows DLCCoast w/ 85 ITMs and 86 deleted references
Game is heavily modded.

**Comment by jbostrus** [comment]
@royrporter does this happen during the initial loading of the mod data, or after editing and trying to save? Do you have other plugins being loaded with the DLC or are you trying with just the DLC? And are you running this normally or inside ModOrganizer2?

**Comment by royrporter** [comment]
The line I listed on the website occurs at 00:18  for FO4edit, not auto clean. All I check marked is DLCCoast.

Using Quick Auto Clean and only DLCCoast selected, I get a pop up window for the same error at 00:21

It is more FYI than an issue for me since auto clean cleaned all the other DLCs fine. I get CTD every 15-45 minutes randomly so I was trying to clean everything. Not a game stopper for me. Just delay in game. LOL, I save very frequently and just restart.

Just started using FO4edit today. Only played FO4 for 20 minutes and got a frozen screen. Dunno if I still get CTD yet. Use LOOT, Removed Mods with deleted nav-meshes. Not worth manually cleaning to me since I use so many mods.
________________________________

**Comment by cursedusw** [comment]
did anyone figure this out I'm getting the exact error as @royrporter

**Comment by cursedusw** [comment]
I dont know if this is advised, but i ran the 64 bit version and it worked with no errors

**Comment by royrporter** [comment]
Thanks, not sure what I did but I got it cleaned using the 64 bit then auto clean.

________________________________

**Comment by cursedusw** [comment]
I think it's a memory error. When I first ran it it gave a pop up that said only use if you are getting insufficient memory errors. I have around 100 mods install

**Comment by ElminsterAU** [comment]
Please retest with 4.0.2j or newer (currently available in #xedit-builds on the xEdit Discord). TIA!
