### ISSUE TITLE
ESM editing broken

### ISSUE THREAD

**Issue by siaccarino** [TES5Edit/TES5Edit#692]
TES5Edit 4.0.2 (F796EF8E)

I can't copy elements (as new records) from esp to esm. The commandline parameters -IKnowWhatImDoing -AllowMasterFilesEdit did not help.

This is something I did since years with an older version of xEdit without any issues.

**To reproduce**
1. Select one or more elements
2. Open Context Menu, "Copy as new record into..."
3. Adapt pre- and suffix
4. No ESM can be selected

**Expected behavior**
ESM can be selected

**Comment by Sharlikran** [comment]
So I will be closing this because this is for issue reports and not observations of functionality. Our issues section is not a forum. Please join discord for now since the comments sections are closed due to user comments.

As far as copying into a master you can't. Copy as override into means into a new plugin. You don't copy into a master. You especially do not copy into the DLC or official Bethesda files. Also if you are not aware you can not and should never edit official Bethesda files. You would only clean them with Quick Auto Clean and then leave them at that.

If you are trying to resolve a conflict section 4 shows that. I would not be able to duplicate the screen shots and text to show it for only Fallout 4 or only Skyrim to make users feel they are looking at something that pertains to the game they are playing. That's not what the docs do. They explain what is a conflict or an override. Then if you wish to make a manual patch do so with a new file. Some context menus will be newer but I have no had time to update everything.
