### ISSUE TITLE
suffix removal during formid copying.

### ISSUE THREAD

**Issue by yarrmateys** [TES5Edit/TES5Edit#722]
xedit has an ability to add and remove prefixes, but only to add suffixes while multiple form ids are being copied. would it be possible to add a suffix removal for that as well?

**Comment by Sharlikran** [comment]
@yarrmateys Just copy the FormID and use a script. That's what the scripting language is for. There are many useful functions that people come up with and to avoid lengthy context menus of things the majority of people won't use, that's why the scripting was added.

Open xEdit and in the apply script window just type suffix and it will show you what is there.

**Comment by ElminsterAU** [comment]
should be implemented in commit referenced above (will be in 4.0.2j)
