### ISSUE TITLE
Fatal: Could not open registry key: \SOFTWARE\Bethesda Softworks\Skyrim\

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TES5Edit/TES5Edit#74]
```
What steps will reproduce the problem?
1. Clicking TES5Edit.exe, trying to use the program.


What is the expected output?
I expected the program to run as it always does.  (Note, up till this evening, 
TES5 is the ONLY program I have ever had that *never* screwed itself up. Go 
figure, eh?)


What do you see instead?
On the right side of the screen -- Fatal: Could not open registry key: 
\SOFTWARE\Bethesda Softworks\Skyrim\
On the Left side, and for the Form fields at the top of the left side, blank.  
Clicking Close gives me a choice of closing, ignoring, or trying to continue, 
but nothing helps anyway.

What version of the product are you using? On what operating system?
TES5Edit_3_0_22_Experimental
Win7


Please provide any additional information below.
The program ran perfectly yesterday (and has since I first downloaded the new 
version); however, it isn't working today.

I have Skyrim set to auto-update; I have the CK set to auto-update.

I validated both Skyrim and CK, deleted and re-installed TES5, the problem 
persists.

I DO NOT have the DLC of Dawnguard or Hearthfire, I have only Skyrim, 
Update.ESM, and High-Res texture packs 1 &2.  I use SKSE, and as I said, until 
today, I never had a single issue with TES5.

Below is the text of the bug report:
date/time         : 2012-10-24, 17:13:00, 653ms
computer name     : ALLA-PC
user name         : Alla <admin>
registered owner  : Alla
operating system  : Windows 7 x64 Service Pack 1 build 7601
system language   : English
system up time    : 8 hours 44 minutes
program up time   : 21 seconds
processors        : 6x AMD Phenom(tm) II X6 1100T Processor
physical memory   : 6345/8189 MB (free/total)
free disk space   : (C:) 346.67 GB
display mode      : 1920x1080, 32 bit
process id        : $1328
allocated memory  : 41.23 MB
executable        : TES5Edit.exe
exec. date/time   : 2012-10-13 10:57
version           : 1.0.0.0
compiled with     : Delphi XE
madExcept version : 3.0o
TES5Edit.exe.mad  : $0002f6a8, $7f37414d, $a2bc96aa
callstack crc     : $8211f496, $8211f496, $8211f496
count             : 11
exception number  : 2
exception class   : EAccessViolation
exception message : Access violation at address 008A3CCC in module 
'TES5Edit.exe'. Read of address 00000000.

main thread ($27c):
008a3ccc +2a0 TES5Edit.exe segment%152 public%17373

thread $1100 (TWorkerThread):
004071ce +5a TES5Edit.exe segment%0 public%286






```

Original issue reported on code.google.com by `Allann...@gmail.com` on 24 Oct 2012 at 10:22

**Comment by adkins2010** [comment]
THAT SOLUTION DOESN'T WORK.  
I ran the Skyrim Launcher so many times, and started the game and ended, and did this repeatedly.  At least provide a more detailed explanation or how-to-fix.  Because, I am doing exactly as you said, and it doesn't fix it.

**Comment by Sharlikran** [comment]
There isn't a more detailed explanation. You don't do this and do that and edit this file and check that box. 

The docs explain what to do

**Comment by adkins2010** [comment]
@Sharlikran 
I got it.  I think that TES5Edit doesn't work with _Skyrim **Special Edition**_.  I found SSEEdit and I think that works with my version.  Thanks, anyways.

**Comment by Sharlikran** [comment]
Yes, that can also be a factor. Once you download the version in releases that I linked. Open the readme.

This program is like anything else that exists. It is hard to know what people will ask and what initial issues they will have. Running the program for the first time user may need to know certain things.

So for the readme it lists all the names the exe can have and explains that if you need it to work with Skyrim, which is just that, Skyrim, then its TES5Edit. Since Skyrim Special Esition has a different folder name for everything we can have the same exe for it but to eliminate the need for different code you just rename the file.

So for Skyrim Special Edition you use SSEEdit. For Fallout 4 it is FO4Edit and all that is in the readme that comes with xedit.

**Comment by TjGRiM** [comment]
So my Skyrim SE updated automatically and since I'm happy with my current mod list I decided to roll it back to the previous version but now my SSEEdit is giving me the same "fatal" error and I just would like to know; is there any way to fix this without running the skyrim launcher? Because if I do that my skyrim will once again be updated which I do not want, but I have activated a few mods (that I had sitting in my list inactive) which LOOT is telling me I should have cleaned.

 Any suggestions would be greatly appreciated.

**Comment by Rrhyon** [comment]
I am having a similar issue, receiving the "Fatal" error from TES5Edit, stating my Skyrim registry cannot be found.  However I was able to locate it in the "Software/WOW6432node/Bethesda Softworks/Skyrim Special Edition".  Presently I am trying to figure out how to make the application see the current location of Skyrim in the registry or move the folder in the registry without breaking anything.

**Comment by ElminsterAU** [comment]
If you are trying to use TES5Edit instead of SSEEdit for SSE you shouldn't expect it to work.

**Comment by Sharlikran** [comment]
@TjGRiM @Rrhyon If you know of the Marvel Universe and Dr. Strange, "Read the entire spell the Warnings come at the end!" So read everything and the warning at the end.

We do not have a way to force things to work. Meaning there are no special command line programs, product keys like you have for Windows, and no configuration files. The procedure is very simple and doesn't require anyone to ask for clarification about how to make our program recognize your install.

I have documentation and when this happens there is a popup that tells you what to do. We have made this that way because people ask it so many times it is difficult for us to keep some kind of communication open to the public. As you notice our comments section is closed. That is for a more serious reason but it would be unfortunate if we had to close our issue tracker. It is for issues only, it is not a forum. This question is not an issue at all as previously mentioned and I even gave the answer already.

If you read above adkins2010 was saying that he tried to use the launcher as was suggested and it did not work. That is either because of system and permissions issues you configured or you have an illegal copy of the game. 

So that all users looking for this issue have something to go over instead of asking our team for an issue we can't really help you with, here is more information. This has already come with the download or displayed on your screen. The only thing you have not seen already is the online documentation.

# Readme file

The first place we provide information is the README.txt

![image](https://user-images.githubusercontent.com/1912426/70079841-5d33d600-15ba-11ea-872a-36ad3b0a1dab.png)

As shown we give you information on which file name works for each game. If you have Classic Skyrim then that is TES5Edit. If you have Skyrim Special Edition then that is SSEEdit. So first you have to be using the properly named EXE with the corresponding game.

# Game Launcher

You have to run the launcher. Some people have Windows permissions set to prevent Steam from updating their game. I am sorry if you have to do that but that is not our issue. You must run the launcher to have Steam configure windows. It is required.

For Skyrim it would look like this:

![image](https://user-images.githubusercontent.com/1912426/70080112-d3d0d380-15ba-11ea-98fe-67a7e69eb8d6.png)

For Skyrim Special Edition it would look like this:

![image](https://user-images.githubusercontent.com/1912426/70080157-e64b0d00-15ba-11ea-8010-cc236e9b8eda.png)

# Solution

Run the launcher and verify you have the proper name of the xEdit EXE for the game you are using it with.

# Other resources that tell you what the solution is:

## The documentation

In section 2.2.6, the overview there is a section for [startup issues](https://tes5edit.github.io/docs/2-overview.html#s_2-2-6).

## The popup window

![image](https://user-images.githubusercontent.com/1912426/70080664-d253db00-15bb-11ea-83b0-bcf56026ef1f.png)

Notice how it says to run the games launcher.

# Warning!

![image](https://user-images.githubusercontent.com/1912426/70080922-53ab6d80-15bc-11ea-8cd5-9a18e7d9021b.png)

If you have configured Steam to only update when you launch the game to prevent auto updates of the game, then your game will update! We are not responsible for reverting your game or updating SKSE/SKSE64 Plugins for the script extender such as HDT and SMP.

**Comment by TjGRiM** [comment]
Considering the nature of the Skyrim modding world I don't think it's
completely ridiculous to ask that your program be able to recognize our
instals in any other manner other than running the game launcher, in fact I
think it's far more ridiculous that your program doesn't simply allow us to
locate our instals manually. That would be a very easy fix to this issue
and it seems like a pretty obvious thing to do given that the launcher
updates the game and many players DO NOT want to update their games.

Another thing, I'm new to modding Skyrim, and in the past month or so I've
watched, read and slept through so many videos and tutorials I've lost
count and like I said before, I'm happy with my current mod list, a large
part of that being that I DO NOT want to watch or read anymore tutorials on
youtube or anywhere, so forgive me if I missed your video from 2013 (that I
don't even think was linked to this thread) but at the time I was really
just trying to avoid all that, so I likely just overlooked it out of
frustration. A frustration admittedly caused by me being new to modding and
not knowing everything I need to know, and Bathesda and Steam for that
pointless update, but also YOUR program for being limited to only being
able to find whatever files it needs via the game launcher. It amazes that
someone had enough smarts to created this program (which is far more than I
can do) but they don't have the smarts to think "hey, this could cause some
issues, let's allow the user to set the path manually" (or whatever would
be required to allow us to fix this issue without having to open the
launcher). I just feel like a very key scenario wasn't taken into account
when creating this program, and that is: lot's of people are trying to
avoid updating their game, and not everyone really knows entirely what
they're doing

Anyways I'll look into setting windows permissions to not allow steam to
update Skyrim, but it would be a lot simpler if your program wasn't so
limited. And another thing, you say "This question is not an issue at
all..." but I beg to differ. The fact that people even need to ask this
question to begin with is the real issue, and why? Because you gave us one
singular way to fix this issue, and for many people that just causes
another issue. Make it possible for us to find the SkyrimSpecialEdition.exe
manually or something, once you do that I'm sure the number of people
asking this question will drop significantly.

**Comment by Sharlikran** [comment]
@TjGRiM I understand that you feel you have seen many videos and read many guides but the error is explained to you in the popup as I mentioned. You didn't have to read any guides or watch videos but they are there for those that need more information or are unclear as to what the game's launcher is. Furthermore as I mentioned all that information is there for future readers so they know what to do to address this issue. It's not specifically for you. 

I understand that some people need older versions for certain Script Extender plugins however, your argument isn't really valid. It doesn't take very long before the Script Extender and its plugins are updated. If Script Extender plugins prevent you from using the current version of the game then take that up with the community. It's not our issue and doesn't have anything to do with xEdit functionality.

In the second paragraph I mention there are is no way to force the program to do things. While true on the information tab there are commands to direct xedit to do things differently. This is helpful for MO2 as an example to redirect the output of the cache. On the information tab there is a command to direct xedit to the data folder using `-D:[CompletePath]\` and the complete path must end in a backslash. I am currently using that since I have two locations on my hard drive for Skyrim because of something I am working on.

To your comments on how robust the program is in regards to how your install is located, xedit will find your game once you have run the games launcher. All tools such as FNIS, Wrye Bash, and LOOT to name a few find your install the same way. Which makes all of them intuitive to anyone such that any new user doesn't have to read anything to get started. Our program uses the Steam configuration that Bethesda's own routines sets up for even its own game to use. Which has been done since Oblivion.

Lastly as the popup mentions we are aware of the two situations that cause the Steam configuration to be removed by Steam. Either the game updated or the user ran the verify integrity of game cache routine to restore system files. That has nothing to do with xEdit functionality and if it makes it inconvenient for you take that up with Steam or Bethesda to address.

Your comments are respectfully noted but deleted. As mentioned in the [readme](https://github.com/TES5Edit/TES5Edit/blob/dev-4.1.4/README.md) our bug tracker is open for issues with the program. However, it is not a forum. You report the issue, you get an answer, in this case it's not a bug, and you respectfully move on.
