### ISSUE TITLE
SSEdit error while loading mods

### ISSUE THREAD

**Issue by TheKarshin** [TES5Edit/TES5Edit#766]
**What is the version of xEdit you are using?**
xEdit 4.0.3 by ElminsterAU

**Describe the bug**
While loading all mods in SSedit - appeared to me with many mods:
[QUST \ FULL - Name] <Error reading string: [EEncodingError] No mapping for the Unicode character exists in the target multi-byte code page>

SSedit loads all mods.
The game is working properly.
I play over 600 hours on my current character and I have never had such errors before with these mods.

**To reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Sharlikran** [comment]
What language and what encoding are you using? For example English is code page 1252. So if I answered my question I would say I am using English with code page 1252 and I start the program with `D:\Games\steamapps\common\SSEEdit\SSEEdit.exe -cp:1252`

Granted I don't need to do that because since I use English then it starts in English and uses code page 1252 automatically.

**Comment by TheKarshin** [comment]
Hello Sharlikran
 
I use Polish language. I don't know how to check the code.
I start the program with
D:/Rozne/Steam/steamapps/common/Skyrim Special Edition/SSEdit

Regards

**Comment by ElminsterAU** [comment]
The error indicates that you have module files that contain strings which are not valid UTF8 strings. A likely reason for that is using skyrim LE module files in SSE, because LE used language specific ANSI codepages, while SSE uses UTF8 for all languages except English.

**Comment by TheKarshin** [comment]
I use several mods converted from LE to SE (44 format). I don't have unconverted mods. Is this problem I have reported to you a serious problem? Can it spoil the game or SAVE?

**Comment by ElminsterAU** [comment]
Resaving an LE mod with non-english characters in SSE CK will not convert the contained strings to UTF8... it's likely that many "converted" mods with non-english characters are technically invalid for SSE...

**Comment by TheKarshin** [comment]
I'm sorry to ask you that - but I don't know anything about it, and I want my Skyrim to be as stable and secure as possible.

This error also applies to mods released on SE, such as "Apocalypse - Magic of Skyrim", "Helgen Reborn".

What should I do - by removing the mods affected by this error? (I hope not)

**Comment by ElminsterAU** [comment]
please show me the first page of your messages log.
this error shouldn't normally affect your save game. at worst some texts are not displaying correctly in game.

**Comment by TheKarshin** [comment]
I hope you meant it
SSEEdit_log.txt](https://github.com/TES5Edit/TES5Edit/files/4007000/SSEEdit_log.txt)

**Comment by ElminsterAU** [comment]
ok, yes. I assume the files for which the `<Error reading string: [EEncodingError] No mapping for the Unicode character exists in the target multi-byte code page>` are showing are in fact translated polish versions of these mods?

**Comment by TheKarshin** [comment]
Some mods with this error are translated into Polish (e.g. Missives - Solstheim, Miss..Falskaar), but most are not translated into Polish.

**Comment by ElminsterAU** [comment]
The issue is that they contain non-UTF8 characters. I'll see if I can implement a codepage fallback for translatable strings in module files, same as it's done for .strings files...

**Comment by TheKarshin** [comment]
I have lost over 600 hours on this character. I used SSEdit many times during this game, but it never showed such errors before (most mods I have from the beginning of the game, of course updated).
Some mods I have translated into Polish myself, some professional translators have translated, most of the mods are in English and this error concerns mods from each of these groups.
The most important thing is that you wrote that this can not spoil the game - I'm calmer.
If I understand correctly then - you will try to "do" something about it - then there will be an update ...
Thank you for your commitment and a very professional approach to an amateur like me.

**Comment by ElminsterAU** [comment]
I have no idea what you mean with "I have lost over 600 hours on this character".

xEdit showing you that the files contain incorrectly formatted strings has absolutely no impact on your game or saves.

Older versions of xEdit have no treated string data encoding as rigorously correct as the current version. You can read about the relevant changes in the What's New.

Fact is:
Skyrim LE expects strings to be in a language dependent ANSI codepage (1250 for polish)
Skyrim SE expects strings to be in UTF8 for any language except English, and ANSI codepage 1252 for English

The error you are seeing comes from the fact that you have module files with strings either in codepage 1250 or 1252, but because you have configured your game for Polish, and it is SSE, it expects all files to be in UTF8.

For strings in module files, xEdit currently shows the error mentioned above if the string is not a valid UTF8 string.

What I can probably implement (I'll have to look into that) is that if it encounters a string where the conversion from UTF8 fails, it just throws the hands up in the air and says "well, the string is probably an ANSI encoded string, treat it like that and hope for the best". (Which is most likely what the game engine does do).

The problem with this (and it will affect both the game and xEdit) is that it's possible that there are strings encoded in some ANSI codepage, which are "valid" UTF8 strings, but which result in different characters when treated as ANSI or UTF8.

**Comment by TheKarshin** [comment]
I can't speak English fluently, which is why I use a translator and he translated it wrongly what I wanted to write.

I meant that I have played over 600 hours so far - not that I "lost" 600 hours of play :)

I more or less understand what the problem is and I hope you can implement it ...

Once, instead of some Polish letters in the name of the weapon (enchant) I had squares, now most are in English.
And ... I have not noticed any strange stamps at present - English mods are in English and Polish mods are in Polish.

"The problem with this (and it will affect both the game and xEdit) is that it's possible that there are strings encoded in some ANSI codepage, which are" valid "UTF8 strings, but which result in different characters when treated as ANSI or UTF8 . "
This statement disturbs me, but I'm probably oversensitive - you wrote earlier that the highest marks will appear in the game for me.

**Comment by TheArel** [comment]
I am having the issue as this player. I have Turkish Windows and my game is SSE English. When SSEdit loads the plugins there is missing string file error coming from even Skyrim.esm and  this is really disturbing since I can't troubleshoot the other problems properly when I click "check for error" is there any way to change this encoding thing?

**Comment by valador** [comment]
Maby exist someone script who be highlight this error? EEncodingError and UnicodeDecodeError, now a'm need open all arrays and visual chech ALL parts of mod, its too long and sometimes miss someone errors :(

**Comment by holydam** [comment]
I have same problem,i want ask you that if you have already slove this question,would you
tell what method did you use to deal this?

**Comment by JJJ562004** [comment]
i got into this error as well  i've aldready run Loot and the game and nothing seem wrong but when i run xEdit , this error orccurred
Here is the ExceptionLog file in its folder

**Comment by JJJ562004** [comment]
I got into this error as well 
I've aldready run Loot and the game and nothing seem wrong but when i run xEdit , this error orccurred
Here is the ExceptionLog file in its folder

[SSEEditException.log](https://github.com/TES5Edit/TES5Edit/files/13987828/SSEEditException.log)
