### ISSUE TITLE
Apply for Github sponsor program

### ISSUE THREAD

**Issue by LexiconCode** [TES5Edit/TES5Edit#828]
There are number of platforms to donate to TES5Edit development. I would encourage you to apply for github sponsorship. They match dollar for dollar donations through the program up to I think $3000. 

https://github.com/sponsors
https://github.blog/2019-05-23-announcing-github-sponsors-a-new-way-to-contribute-to-open-source/

**Comment by ElminsterAU** [comment]
Thanks. I'll have a look at that.

**Comment by ElminsterAU** [comment]
I've applied for the GitHub Sponsership program (the donation matching program doesn't exist anymore for new applications since 1st January btw).

In the meantime, I've added the existing donation methods to the Sponsor button (and will obviously add the github one once they have accepted my application).

**Comment by ElminsterAU** [comment]
GitHub sponsoring is now possible both with the Sponsor button on the TES5Edit repo as well as directly on my user profile.
