### ISSUE TITLE
Request : If file save fails.  Offer retry option before closing xEdit.

### ISSUE THREAD

**Issue by Delgathar** [TES5Edit/TES5Edit#842]
Hello,

Frequently I need to have multiple apps open as I edit records: second Xedit, Loot, Creationkit, etc., which locks the files.  When I forget to close the other apps first before closing Xedit, the save fails and my work is lost.  If the save and rename fails on close, please make xEdit pause and give the user a chance to close the other apps and retry the save.

Thank you very much.

**Comment by zilav** [comment]
Read documentation, particulary about direct saves
https://tes5edit.github.io/docs/18-whatsnew.html

Then you can save over original file without closing xEdit with Ctrl+S at any time.

**Comment by VlitS** [comment]
Additionally, if xEdit fails to rewrite the save for the original file due to another program holding onto it (such as it being open in the CK), there should be a up to date save (I want to say in the same location as the plugin itself). 

When xEdit saves it creates that save, then tries to rename the old file to have a .backup.DATE at the end (or removes it if you have backups disabled), and then renames the plugin.save.DATE file to the normal plugin name. It works that way specifically for cases like what you are talking about.

**Comment by Delgathar** [comment]
Thank you.
