### ISSUE TITLE
Plugins with no masters can't resolve references to hardcoded records

### ISSUE THREAD

**Issue by Infernio** [TES5Edit/TES5Edit#888]
**What is the version of xEdit you are using?**
TES4Edit 4.1.3d EXTREMELY EXPERIMENTAL (CC3D3763) starting session 2020-12-04 13:47:24

**Describe the bug**
xEdit can't resolve references to hardcoded records in plugins with no masters. Tested in Oblivion, but probably applies to all games.

**To reproduce**
1. Download [Oblivion.zip](https://github.com/TES5Edit/TES5Edit/files/5642809/Oblivion.zip)
2. Place `Oblivion.esp` in `Data`
3. Open `Oblivion.esp` in xEdit
4. Note how all of the records show `[FORMID HERE] <Error: Access violation at address 00C70CA0 in module 'xEdit.exe'. Read of address 00000000>` in their record headers

**Expected behavior**
The hardcoded `Oblivion.exe` should have been loaded, allowing those references to be resolved. Probably a consequence of the fix for #848.

**Additional context**
`Oblivion.esp` was created entirely in the TESCS, by loading no masters and marking all accessible records as modified.

**Comment by ElminsterAU** [comment]
The AV was already fixed sometime between 4.1.3d and now, the commit above just adds the whatsnew entry for it.

xEdit is not designed to load the "hardcoded" .exe entry without loading the official game master first, so it won't do that when loading only this oblivion.esp. It wouldn't help either, because the hardcoded file only contains the hardcoded records which are not already present in the .esm, and loading it after the .esp would incorrectly show the .exe as overriding the values from the .esp.

You can load Oblivion.esp together with Oblivion.esm, and despite the .esp not having the .esm as explicit master, it will correctly recognize the hardcoded records as such:

![image](https://user-images.githubusercontent.com/27037648/124911534-32c8bb00-e030-11eb-9b5b-8cfa68ed1287.png)
