### ISSUE TITLE
Unable to use FO4Edit to quick auto clean

### ISSUE THREAD

**Issue by Melkiah147** [TES5Edit/TES5Edit#889]
**What is the version of xEdit you are using?**
FO4Edit 4.0.3 (819FA7E8)

**Describe the bug**
The main Fallout4 master file is not selectable in the quick auto clean menu, where as all DLC can be selected. The main file can be selected when using FO4Edit.

**To reproduce**
1. Open Quick Auto Clean

**Expected behavior**
To be able to select the main file so as to clean it.

**Screenshots**
![image](https://user-images.githubusercontent.com/76262192/102696784-eb4b2080-41fe-11eb-91aa-06e371edd7c5.png)
![image](https://user-images.githubusercontent.com/76262192/102696793-f9993c80-41fe-11eb-9456-9979e8450f7a.png)

**Comment by Infernio** [comment]
You can't clean the game master. Both ITMs and UDRs need the cleaned file to actually have a master against which records can be compared. Since the game master doesn't have a master (obviously, it's always the first plugin after all), cleaning it doesn't make any sense, wouldn't do anything and is hence impossible to even attempt in QAC mode.

**Comment by ElminsterAU** [comment]
What he said.
