### ISSUE TITLE
Clicking File Header after compacting forms for ESL doesn't take to you View Tab

### ISSUE THREAD

**Issue by Elaura1970** [TES5Edit/TES5Edit#935]
xEdit 4.0.3
For Skyrim SE
Run through MO 2.4.2 rev1a5dd6c7

Clicking File Header after compacting forms for ESL doesn't take to you View Tab

**To reproduce**
1. Right click on any mod in the left pane
2. Click on 'Compact FormIDs for ESL'
3. Wait for it to finish 'Done: Changing FormIDs, . . .'
4. In left pane open the mod tree, left click File Header
5. Right-hand tab stays on Messages and doesn't jump to View tab.

**Expected behavior**
I expected upon left clicking File Header for the right pane to automatically go to the View tab as it does if you click it before compacting FormIDs.

**Additional context**
It would also be nice if the tree of the affected mod would either already be expanded after completing Compacting FormIDs, or if add ESL flag was in the right click context menu.
In addition, it would be VERY convenient if XEdit had the option to save mods as Form 44 when changes are made (as WryeBash does).

**Comment by ElminsterAU** [comment]
That's because you had the file header selected before performing the operation already, so clicking it again afterwards doesn't change the selected node. Just click on the view tab if you want to go back to where you were before it switched to the messages tab.

Also, to quote @Infernio in regards to Form 44 and WB: That's not a thing :thonk:
