### ISSUE TITLE
There are no modules in the data folder.

### ISSUE THREAD

**Issue by abysskeeper** [TES5Edit/TES5Edit#960]
I use Skyrim LE with Mod Organiser 2, and my Skyrim is directly installed on C: drive rather than Program files, I've tried many things, including running Skyrim Launcher over and over again both through MO2 and without MO2 as it was the only solution that I've found for this error online, but It didn't work at all. Whenever I run TES5Edit 4.0.3 through Skyrim I keep getting this same error.
![tes5](https://user-images.githubusercontent.com/76806320/134807497-92ffe970-3904-4cf9-bf85-ffbfa0d674de.png)

**Comment by ElminsterAU** [comment]
A) this is a support question and not a bug report, so it belongs on the xEdit discord instead of here.
B) based on the paths in the screenshot, I believe this is not a steam version of Skyrim LE. To my knowledge, there are no legal non-steam versions of skyrim LE. We don't provide support for use of xEdit with pirated versions of games. But if you do have a legal steam version of skyrim, feel free to drop by the discord for help.
