### ISSUE TITLE
FO4, incorrect HITMEs

### ISSUE THREAD

**Issue by StuAhpla** [TES5Edit/TES5Edit#991]
```
Changing FormID [00000039] in file "caliber-patches.esp" to [FE032039]
Record is referenced by 125 other record(s)
Renumbered  \ [FE 039] caliber-patches.esp \ [2] GRUP Top "WEAP" \ [0] M4k4rovCWPPSh "PPSh-41" [WEAP:00000039]
Warning: Record [GLOB:00000039] in file Fallout4.esm is being overridden by record [WEAP:4C000039] in file caliber-patches.esp.
```

Version 4.0.4.
For some unknown reasons several records that should be overriding FE032 (ESL 032) are instead trying to override 00 (fallout4.esm). Any attempts to change the formID of the patched records to whatever they were supposed to be doesn't work. It seems to affect a random number of ESLs with nothing in common with them. 
Loading the same order of plugins in an earlier version (4.0.1) does not have this issue. It may be caused by an issue with xEdit trying to handle record overrides from ESL files

**Comment by VlitS** [comment]
A few things:
1) When reporting things like this, you should include the plugin in question (either the actual file, or at least a link to it), so that Elminster can observe the behavior
2) That is not what a HITME is. HITMEs are when the internal formID prefix (the one actually written in the file, that references the masterlist in the file header) of some records is greater than what would normally point at new records.* 
3) 4.0.1 was released before the expanded ESL space (001 to 7FF) was implemented in the game
4) If the plugin version in the file header is 0.95 instead of 1.0, the game won't let it use that expanded space.
5) Plugins that don't have Fallout4.esm as a master will still override hardcoded records the way that they used to before the expanded ESL formID space was implemented in the game.

I suspect either 4 or 5 apply to this plugin, possibly both, but cannot confirm without the plugin. 


*If you are interested in learning more about HITMEs, what can cause them, and why they are bad, I'd be happy to explain on the discord (a bit too long of an explanation to include here, since the issue is about something different).

**Comment by StuAhpla** [comment]
It seems to have been case 4, the patching plugin was version 0.95 while the original plugin was 1.00. I tested it by changing the version in the HEDR with a plugin I had a backup of in case it broke things and it seems to now be overriding records as expected. I'll keep an eye on it though to make sure that there's no other side effects from changing the header version but so far it seems to have fixed the immediate problem.
The mods I tested were 
https://www.nexusmods.com/fallout4/mods/52201 (version 1.1 but the mod seems to be hidden as of this post)
and
https://www.nexusmods.com/fallout4/mods/52245 (esl version 1.0)

**Comment by VlitS** [comment]
Only "side effect" you should see with changing the version number is that older versions of FO4 won't be able to load the plugin  (should only really matter for FO4VR users, at this point the relevant update is something like 2 years old).  

But if the original plugin had those lower formIDs, it was already incompatible with those older versions of the game.

**Comment by StuAhpla** [comment]
I'm using the most up to date version for FO4 so this shouldn't be an issue. The issue is likely resolved then.

**Comment by jbostrus** [comment]
This makes total sense.

The HEDR version 0.95 will force records with form numbers < 0x800 whether overrides or new to the plugin. Older versions of the game prior to the HEDR version upgrade handled any form number < 0x800 has a hard coded override. The older versions of xEdit didn't have the same logic so if it wasn't an explicit override but a new plugin record it would exhibit the behavior noted, which is incorrect as to how the game handles it.

By having the master with HEDR version 1.0 it allows the lower form numbers without causing it to be a hard coded override. But then having the patch trying to override that form, and only having the HEDR version 0.95 makes xEdit operate as the game would. The patch record then becomes a hard coded override.
